### ISSUE TITLE
Downloaded images always get the PNG extension (even gifs)

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#102]
#### General Information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** eg 0.1.5, or commit

#### Steps to reproduce
1. Search for any image (eg. Gif)
2. Long click it and select download
#### Expected result

**What is the expected output?** 
Image gets proper extension (gif, PNG, jpg)

**What do you see instead?**
All images get the PNG extension. That's fine in most cases, but gif files should rather have the gif extension.

**Comment by gsantner** [comment]
Issue merged into #107
