### ISSUE TITLE
Additional options for NavSlider ; Update settings hierachy

### ISSUE THREAD

**Issue by gsantner** [gsantner/dandelion#104]
#### General information

* **App version:**  0.1.6-next
* **App source:** HEAD

#### Steps to reproduce

1. Open NavSlider
2. No Option for Reports

#### Expected result
**What is the expected output?** 
* An Option for "Reports"
* Suburl for `PODADDRESS/reports`
* Available only to Admins/Mods
* Divide navslider visibility options into user, general and admin categeories
    * Personal (Profile, Contacts, ....)
    * General (Exit app, About)
    * Admin (Reports / Statistics (dunno if available :) ) 

**What do you see instead?**
No such option

**Comment by vanitasvitae** [comment]
Reworked in #110
