### ISSUE TITLE
Navslider entry "Profile" takes user to search form on first start

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#117]
#### General information

* **Device:**   
* **Android Version:**  
* **App version:**  HEAD
* **App source:**  
* **Pod:** 
* **Diaspora pod version:** 

#### Steps to reproduce

1. Open App for first time or chage account
2. Log in to account
3. Click on Profile picture / Profile Entry

#### Expected result
**What is the expected output?** 
App displays users profile

**What do you see instead?**
App displays the search form of the mobile interface

This is caused by the DiasporaUrlHelper or AppSettings not being updated after the profile has been loaded completely. The DiasporaUrlHelper's AppSettings object still returns "" on getProfileId(), so the search form gets loaded instead of the profile.

Also the profile picture and name are not set to default when logging out of account.

I tried to re-set DiasporaUrlHelper in MainActivity.onUserProfileNameChanged(), but since the name is not cleared when logging out, this does not work as intended. I hope, you find a way to fix this @gsantner :)

**Comment by gsantner** [comment]
After first login you have to wait some time to get this details. The id's can't be extracted when nothing is available.. There is no way to resolve this.

**Comment by gsantner** [comment]
This is now implemented/fixed, including navheader reset. check it out on master.
