### ISSUE TITLE
Rework sharing data via Intent

### ISSUE THREAD

**Issue by gsantner** [gsantner/dandelion#12]
Improve/Rework sharing data via Intent
- Remove ShareActivities
- Provide one entry point in the app to share to
- App scans the share intent and looks which data is included
- Allow user to select which parts of message he wants to include in his diaspora post
- Allow picture sharing into the app (#11 )

**Comment by ClubWDW** [comment]
So, then my question is this. . . .I see an update to version 1.5 dated 04/09/16. However, I also wee a warning that says "This app has been discontinued in favor of Diaspora" which redirects to version 0.1.0, which hasn't been updated since it came out on 03/30/16. Which is the one that is actively being developed/updated?

**Comment by ghost** [comment]
I reworked the share_activity again. It can now recognize the difference between:
- text with extra_subject
- text with only extra_text
- images

Also out is now only one share activity. So next point would be to implement receiving pictures. But as said, I've no idea how to do that. I marked it with todo in activity and manifest.

**Comment by ClubWDW** [comment]
When will we be seeing this show up in F-Droid to download? I am still
showing version 0.1.0

On Friday, April 15, 2016, Gaukler Faun notifications@github.com wrote:

> I reworked the share_activity again. It can now recognize the difference
> between:
> - text with extra_subject
> - text with only extra_text
> - images
> 
> Also out is now only one share activity. So next point would be to
> implement receiving pictures. But as said, I've no idea how to do that. I
> marked it with todo in activity and manifest.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/Diaspora-for-Android/diaspora-android/issues/12#issuecomment-210633831

## 

Bryan Belt

I prefer to use encrypted email. My public key fingerprint is 8DB3 1568
E467 F703 2C63 E444 821C 645D EBDC 9F9A. Learn why your privacy matters by
watching this video - https://youtu.be/pcSlowAhvUk and then learn how to
protect and encrypt your email by watching this video -
https://youtu.be/Ro3MSBS9w-A

**Comment by vanitasvitae** [comment]
I removed the ShareActivity and moved content handling methods to MainActivity. Sharing text works now as intended.
