### ISSUE TITLE
"+" Obscures "Reply" button in Messages when entering reply to message

### ISSUE THREAD

**Issue by VikOlliver** [gsantner/dandelion#122]
#### General information

* **Device:**   HTC One
* **Android Version:**  N/A
* **App version:**  -- See in About -> Debug. eg 0.1.5, -- <== Does not exist in this app version
* **App source:** Google Play Store
* **Pod:** 
* **Diaspora pod version:**

#### Steps to reproduce

View a message with more than one screenful of replies.

Scroll to the bottom and add text to the exnisting new message edit box.

Observe big "+" squatting where the "Reply" button is.

#### Expected result

It would be reasonable to expect the "+" icon to go away when the reply message edit box has content, as its functionality is largely redundant at this point.

**Comment by gsantner** [comment]
Hello @VikOlliver,
you seem to have Diaspora Native Webapp installed, an very old version. Please update to the latest version. It's available on [F-droid](https://f-droid.org/repository/browse/?fdid=com.github.dfa.diaspora_android) and [GitHub](https://github.com/Diaspora-for-Android/diaspora-android/releases).

The `+` button war removed a long time ago.
