### ISSUE TITLE
Add http and onion pods to intent filter list in Manifest

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#124]
#### General information

* **Device:**   
* **Android Version:**  
* **App version:**  HEAD
* **App source:**  
* **Pod:**  
* **Diaspora pod version:**  

The app should offer itself to open onion and http pod links the way it already does for https pods.

**Comment by gsantner** [comment]
👎  Downvote for normal http pods - Pods should use https, I don't think we should support pods transfering date over insecure http connections.  
\- But yes, for onion-http its okay.

**Comment by gsantner** [comment]
I just checked the current Manifest.
http -onions are already in the intent filter, see
<https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/AndroidManifest.xml#L74>.

Closing.
