### ISSUE TITLE
no confirmation pop-up when trying to reshare a post

### ISSUE THREAD

**Issue by stragu** [gsantner/dandelion#127]
#### General information

* **Device:**   Fairphone 1
* **Android Version:**  4.2.2
* **App version:**  0.2.0a
* **App source:**  F-Droid
* **Pod:**  joindiaspora.com
* **Diaspora pod version:**  0.6.1.0

#### Steps to reproduce

1. Try to reshare someone's post

#### Expected result
**What is the expected output?** 

Pop up to ask for confirmation

**What do you see instead?**

Nothing.

I am pretty sure this problem was introduced by 0.2. I could reshare without a problem before the update.

If I use a browser (Firefox for Android) and use the mobile view for my Diaspora pod, resharing works fine, the popup appears and I can confirm the action

**Comment by vanitasvitae** [comment]
Hm, that's strange. I don't think we changed something that might have broke that functionality. I'll investigate that. Thanks for the bug report :)

**Comment by vanitasvitae** [comment]
I can successfully reproduce this behavior in an emulator running JellyBean (Api 17). I'll try to come up with a fix for the next release.

**Comment by vanitasvitae** [comment]
This is now fixed.

**Comment by stragu** [comment]
Great, thanks!
