### ISSUE TITLE
[diaspora-fr.org] HTTP 500 on "liked" & "commented" shortcuts

### ISSUE THREAD

**Issue by Pafzedog** [gsantner/dandelion#131]
#### General information

* **Device:**   LG G3 d855
* **Android Version:**  Android 6.0.1
* **App version:**  0.2.1
* **App source:**  F-Droid
* **Pod:**  diaspora-fr.org
* **Diaspora pod version:**  0.6.99.0-p7e4de4cb

#### Steps to reproduce

1. unhide the slider menu
2. touch "Aimés" (liked) or "Commentés" (commented) shortcut 
3. 500 - Internal server error

If I switch to non mobile version in bottom menu, page is well displayed

**Comment by gsantner** [comment]
Can you describe the difference between `diaspora-fr.org` and `framasphere.org`? I always get redirected to framasphere when visiting `diaspora-fr.org`. 
-> And maybe theres no redirect for comments/liked posts.

**Comment by gsantner** [comment]
I cannot register and therefore test whats wrong on your pod. As the pod tells it is some kind of test server there might be some server-side code breaking things.

**Comment by Pafzedog** [comment]
Understand, I'll take in touch with my podmin and will give you feedback

**Comment by vanitasvitae** [comment]
@Pafzedog: try to visit commented and liked in the mobile website (take a look at diaspora-fr.org/mobile/toggle to switch between normal and mobile site) with a browser (either using your phone or a computer). This is most likely a problem with your pod.

**Comment by Pafzedog** [comment]
Yes, you are right ! 
Podmin is aware and issue is open on Diaspora Github.
thanks.
