### ISSUE TITLE
Links with # character get split up

### ISSUE THREAD

**Issue by noplanman** [gsantner/dandelion#132]
#### General information

Issue probably happens [here](https://github.com/Diaspora-for-Android/dandelion/blob/dd4af48b8ef677d96dcb5a7deb8394df80a2a8f4/app/src/main/java/com/github/dfa/diaspora_android/ui/HtmlTextView.java#L84), in the regex pattern.

* **Device:** Galaxy S3 (GT-I9300)
* **Android Version:** 6.0.1
* **App version:** 0.2.1
* **App source:** F-Droid

#### Steps to reproduce

1. Create / open a post with a link that has a "#" somewhere in the link text.
2. See how the app splits up the link.

#### Expected result
**What is the expected output?** 
`[My #hashtag link](https://example.com/my-link)`
[My #hashtag link](https://example.com/my-link)

**What do you see instead?**
`[My](https://example.com/my-link) [#hashtag](https://my.pod/tags/hashtag) link`
[My](https://example.com/my-link) [#hashtag](https://my.pod/tags/hashtag) link

**Comment by vanitasvitae** [comment]
Can you test, if this happens when you create a post using the mobile website of your diaspora* pod?

I guess this is an upstream issue of diaspora*

**Comment by noplanman** [comment]
You are right, the link also gets split up in the mobile website of the pod.
Will post the issue directly on the d* repo then, thanks!

**Comment by vanitasvitae** [comment]
Thank you for reporting anyway :)
