### ISSUE TITLE
Copy image URL

### ISSUE THREAD

**Issue by noplanman** [gsantner/dandelion#136]
#### General information
When long-pressing an image, it would be great to have an option to just get a link to the image file. The link itself is displayed at the top of the popup, a tap (or another long-tap) on it to copy it would be nice.

* **Device:** Galaxy S3
* **Android Version:** Android 6.0.1
* **App version:** 0.2.2 (12)
* **App source:** F-Droid

**Comment by gsantner** [comment]
Attaching to #107

**Comment by noplanman** [comment]
Aye, missed that one, sorry..
