### ISSUE TITLE
Share to Telegram (or anything else) not working

### ISSUE THREAD

**Issue by noplanman** [gsantner/dandelion#137]
#### General information
When long-pressing an image and sharing it with a Telegram contact, nothing happens.
No message, no shared URL or picture, nothing.

**Update:** It is due to the fact that dandelion* doesn't create the `/storage/emulated/0/Pictures/Diaspora` folder.
After manually creating the folder, sharing works perfectly!

* **Device:** Galaxy S3
* **Android Version:** Android 6.0.1
* **App version:** 0.2.2 (12)
* **App source:** F-Droid

**Comment by gsantner** [comment]
* <https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/java/com/github/dfa/diaspora_android/web/ContextMenuWebView.java#L113>
* <https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/java/com/github/dfa/diaspora_android/web/ContextMenuWebView.java#L152>

this part of code was somewhere else before. Which included checks and mkdir calls. The Diaspora folder is not created now

**Comment by gsantner** [comment]
Moving over to #107

**Comment by vanitasvitae** [comment]
This is now fixed.
