### ISSUE TITLE
Dandelion crashes when uploading image to post

### ISSUE THREAD

**Issue by theatre-x** [gsantner/dandelion#139]
#### General information

* **Device:**   Samsung Galaxy J1
* **Android Version:**  5.1.1
* **App version:**  0.2.2
* **App source:**  F-Droid
* **Pod:**  ShrekIsLove
* **Diaspora pod version:**  0.6.2.0

#### Steps to reproduce

1. Write a post
2. Press the little camera button for uploading a photo
3. Exit out of the photo selector
4. Press the camera button again

#### Expected result
**What is the expected output?** 
The photo selector to reappear

**What do you see instead?**
My home screen since Dandelion crashes

#### Debug output

I couldn't get a log of the issue for some reason. Literally spent 45 minutes trying to obtain one with aLogcat, Termux, and other apps.

**Comment by vanitasvitae** [comment]
I can reproduce this. Will see, if I find time to fix this in the next days. Thank you very much for the bug report :)

**Comment by Raulvo** [comment]
Hi, I experienced this issue too.

**Comment by vanitasvitae** [comment]
This is now fixed. Had to literally just remove two lines of code.

**Comment by theatre-x** [comment]
Hooray! Thanks! :)
