### ISSUE TITLE
"New-notifications-indicator" freaks out when there are new notifications for the user

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#14]
Hi!
On my device (Nexus 5, CopperheadOS) the black bar on the bottom of the screen jumps up and down very fast when I have unread notifications.

**Comment by gsantner** [comment]
We are currently discussing what comes next and will submit the corresponding issues to GitHub soon.
You are right that also happens on my devices sometimes, the notification part of the app will get new features with notifications (#6), which will also resolve this issue. We are always open for contributions, thanks for your previous work.

**Comment by moshpirit** [comment]
Same here: Android 6.0 with the 0.1.1 and 0.1.2 from F-droid

**Comment by vanitasvitae** [comment]
I changed it now, so that the notification can only be shown when it's hidden. So It may pop up multiple times, but in a far more "unfreaky" manner (lower frequence).
