### ISSUE TITLE
Create first-start dialog telling the user that we do not distribute through GPlay

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#140]
#### General information

* **Device:**   
* **Android Version:**  
* **App version:**  
* **App source:**  
* **Pod:**  
* **Diaspora pod version:**  

#### Steps to reproduce

1. User opens app for the first time

#### Expected result
**What is the expected output?** 
An alertdialog tells the user that the app is currently not distributed through Google Play, but through free libre distribution channels only.

**What do you see instead?**
Nothing yet

**Comment by gsantner** [comment]
Maybe let's generalize this: Add a first start dialog, where people can see what this app can do. That it is licensed free/GPL and list the only official download links, excluding and noting about gplay

**Comment by gsantner** [comment]
Maybe let's generalize this: Add a first start dialog, where people can see what this app can do. That it is licensed free/GPL and list the only official download links, excluding and noting about gplay situation

@vanitasvitae What about, let's create a dummy app, which just says download the app somewhere else and uninstall this one. Then the app id is reserved on gplay and somebody else cannot upload anyway.

**Comment by vanitasvitae** [comment]
Nice idea :) how about naming it "dandelion* installer" or something but keeping the appid the same as dandelion. Also keep the version number very low, so dandelion* always is "more up to date"

**Comment by gsantner** [comment]
@vanitasvitae  +1
Can you upload it on G-Play then?

**Comment by gsantner** [comment]
LICENSE (with store notice)  +Changelog Dialogs now coming up. Implemented in <https://github.com/Diaspora-for-Android/dandelion/commit/cc6f3d2aa7445f94efa82225b3adcf081a2c202c>
