### ISSUE TITLE
question about multi account managing

### ISSUE THREAD

**Issue by Candidesk8** [gsantner/dandelion#143]
#### General information
* ** FairPhone FP1U :**
* ** Android 4.2.2 :**
* ** pod.framasphere.org :**
* ** 0.6.0.0-pba27cf8f :**
* ** F-Droid :**
* ** 0.2.2 (12) :**

#### Steps to reproduce
not really a bug, this is much a question...
when changing account (super useful feature, thanks!), 
the use of the keyboard is not so intuitive, so I entered several account reference before reaching the good one.
since, this wrong account reference always appear. how do I clear this?

#### Expected result
**What is the expected output?** 
having only the right account stored in memory

**What do you see instead?**
all the mistake I made before...

**Comment by vanitasvitae** [comment]
There is no mechanism implemented to do only that right now. You could try to delete the WebView cache (dandelions settings -> network -> Clear WebView cache) and if that doesn't help you could delete app data (dandelion settings -> debugging -> miscellaneous -> reset. Warning: this will erase your account credentials and app settings!)

**Comment by Candidesk8** [comment]
Thank you for answering!
It worked with deleting app data, whereas it didn't with clearing the
webview cache.
I had to type again my references, but now it's all working fine.
