### ISSUE TITLE
Aspect preference for posting not taken into account

### ISSUE THREAD

**Issue by xuv** [gsantner/dandelion#146]
#### General information

* **Android Device:** Nexus 5X
* **Android API Version:** 7.1.1
* **App version:** 0.2.2 (12)
* **App source:** F-Droid
* **Pod version:** 0.6.3.0-pec286297

#### Steps to reproduce

1. Click 'pen' icon at the botton of the app
2. New post page is opened with "All aspects" selected by default

#### Expected result
**What is the expected output?** 

I would expect to have my "preferred aspect" being selected as defined in my preferences on my pod. In my case, that is "Public".

**What do you see instead?**
Post is set to "All aspects".

**Comment by vanitasvitae** [comment]
Unfortunately thats an upstream issue with diaspora's mobile view. There's nothing we can do about it.

**Comment by xuv** [comment]
Ho, right. Of course. Thx.

**Comment by vanitasvitae** [comment]
Nevertheless thank you for your report :)

**Comment by xuv** [comment]
No problem. For documentation purpose onlx, issue already filed upstream here: https://github.com/diaspora/diaspora/issues/7333
