### ISSUE TITLE
changelog in f-droid don't updated

### ISSUE THREAD

**Issue by lupa18** [gsantner/dandelion#149]
It's still showing v 0.2.2 in changelog link

**Comment by gsantner** [comment]
Press the top right top button to refresh. you can also reset appdata of fdroid, if it won't update cache anymore.

If this is really just about the changelog file: Thats not related to f-droid in any way. We just posted it on our diasp.org account, not in the file yet.

**Comment by vanitasvitae** [comment]
@gsantner he talks about the CHANGELOG.md, which is in fact not updated yet.

**Comment by vanitasvitae** [comment]
I updated the changelog.

**Comment by lupa18** [comment]
yes ! thanks !!
