### ISSUE TITLE
Can't upload pictures

### ISSUE THREAD

**Issue by PolynomialDivision** [gsantner/dandelion#15]
Hi,
when I want to upload a picture to my pod "pod.gerasporade.de" this message appears:

![uploadingphotobug](https://cloud.githubusercontent.com/assets/10708466/14403333/15f4a03a-fe53-11e5-81a4-720ea9e16a0b.jpg)

After clicking ok nothing happens.

**Comment by gsantner** [comment]
Quick workaround: Select Documents/Gallery, not Camera for the pictures. Got the same pod, and happend also to me. We are currently low on resources (time), and uploading is also definitely a thing we want to resolve. We are always open for contributions from the community.

**Comment by PolynomialDivision** [comment]
@de-live-gdev This workaround isn't working for me. I think it has something to do with the file size because I'm able to upload smaller images (screenshots).

**Comment by vanitasvitae** [comment]
Is this still the case? It works fine on my device, both for photos and images from eg. gallery.

**Comment by vanitasvitae** [comment]
Closed: Can't reproduce and no feedback. Please reopen this, if you face the issue.
