### ISSUE TITLE
Replace notifications dropdown menu with drop down icon bar

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#150]
#### General information

* **Android Device:**
* **Android API Version:** 
* **App version:**
* **App source:**
* **Pod version:**

#### Steps to reproduce

1. Click the notification bell with drop down menu enabled

#### Expected result
**What is the expected output?** 
A nice toolbar with different icons representing different notification types appears below the top toolbar

**What do you see instead?**
The textual drop down menu appears

As requested by ravenbird

**Comment by gsantner** [comment]
@vanitasvitae Why not have both?
Adding icons to Toolbar-Menu Entries is possible. No additional layout or stuff needed.

**Comment by vanitasvitae** [comment]
This is now fixed. Here is a preview:
![Preview](https://cloud.githubusercontent.com/assets/7854206/23683184/de41fee4-0397-11e7-8768-1859d01f3f00.png)
