### ISSUE TITLE
Move diaspora-for-android.github.io page to dandelion.github.io

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#154]
It could use a visual and informational update anyways :)

**Comment by gsantner** [comment]
@vanitasvitae not possible.
dandelion.github.io belongs to
github.com/dandelion .
not to us (github.com/diaspora-for-android).

I am considering our diasp.org profile as our homepage currently

**Comment by vanitasvitae** [comment]
I think it is possible. You can publish a site with a custom URL (in settings)

**Comment by gsantner** [comment]
@vanitasvitae Half wrong, half right. we can publish as diaspora-for-android.github.io, or in any subfolder of it.
we can also publish to any other domain.
But we cannot publish to github pages of other users!
.*.github.io   is not available to us. only username.github.io

**Comment by vanitasvitae** [comment]
Ah okay :/ Can we rename the organization? Or does that break all the links?

**Comment by gsantner** [comment]
@vanitasvitae sure we can. but not to dandelion. this one is reserved by some framework.

https://github.com/dandelion

Maybe dandelion00 is free.
About breaking: We would have to rewrite all URLs.

Short: We wont have any benefit of rename.
