### ISSUE TITLE
Different launcher icon for secondlion* flavor

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#155]
#### General information

* **Android Device: Doesn't matter**
* **Android API Version: Doesn't matter** 
* **App version: Head**
* **App source: Doesn't matter**
* **Pod version: Doesn't matter**

#### Steps to reproduce

1. Install dandelion\* app
2. Install secondlion\* app

#### Expected result
**What is the expected output?** 
The apps are easily distinguishable by different icons

**What do you see instead?**
Both apps have the same icon

It would be nice to have a different colored icon for secondlion.

**Comment by gsantner** [comment]
I'm testing something like that currently on <https://github.com/gsantner/memetastic>. I'm gonna see what works best.

**Comment by gsantner** [comment]
![screenshot_20170319-200443](https://cloud.githubusercontent.com/assets/6735650/24083936/23efe206-0ce1-11e7-9e70-1adf99472068.png)

![screenshot_20170319-200453](https://cloud.githubusercontent.com/assets/6735650/24083938/2b5e62e2-0ce1-11e7-8717-2bd40beeefce.png)

![screenshot_20170319-201807](https://cloud.githubusercontent.com/assets/6735650/24083948/52c328b8-0ce1-11e7-9cf6-fbe435f05a66.png)
