### ISSUE TITLE
Contacts sidebar entry brings user to "my activities" instead of contacts

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#156]
#### General information

* **Android Device:**
* **Android API Version:** 
* **App version:** latest head
* **App source:**
* **Pod version:**

#### Steps to reproduce

1. Click contacts menu entry in slider

#### Expected result
**What is the expected output?**
App opens contacts list

**What do you see instead?**
App loads for ~ 5 secs and then loads my activities.

This is likely related to upstream changes, but we have to reflect those changes in the app.

**Comment by gsantner** [comment]
hm...we will need some kind of version check to determine where to go

**Comment by gsantner** [comment]
Thats not a diaspora/upstream change. Theres a missing switch-case break statement ;)
