### ISSUE TITLE
change text in "shared-by-notice"

### ISSUE THREAD

**Issue by ghost** [gsantner/dandelion#159]
#### General information
Currently, posts get "via #dandelion" at the bottom if this option is selected. I'd prefer if the tag would be replaced with a link to the dandelion account or project page. Following the tag #dandelion is currently useless as the postings naturally deal with all kinds of topics. 

* **Android Device:**
Any
* **Android API Version:** 
Any
* **App version:**
0.2.4
* **App source:**
F-Droid

**Comment by vanitasvitae** [comment]
Yeah, we actually thought about that already. The issue is, that we dont want to clutter the post with too much information. A shortened link would be nice, but which provider to use?

Edit: There is dia.so, @gsantner what do you think?

**Comment by ghost** [comment]
IMHO `via [dandelion*](https://diasp.org/u/dandelion00)` is **not** too much clutter, but I'll leave that up to you guys. Good to know that this is on your radar already. Thanks!

edit: forgot "not"

**Comment by vanitasvitae** [comment]
@Schwoggel thank you for your feedback anyway :)

**Comment by gsantner** [comment]
what about adding a horizontal rule?
```
_______
shared via [dandelion*](/people?q=dandelion00%40diasp.org) / #dandelion


```

**Comment by vanitasvitae** [comment]
yeah that may be nice. Does it draw the line in diaspora?

**Comment by gsantner** [comment]
Yes. you can see our `release posts` how it looks like.

Note the `/people?q` allows pod independent linking to our account, without any additional service required

**Comment by gsantner** [comment]
![screenshot_20170415-102738](https://cloud.githubusercontent.com/assets/6735650/25062131/6c922394-21c6-11e7-9a2f-70f16aa7a5ed.png)
![screenshot_20170415-102755](https://cloud.githubusercontent.com/assets/6735650/25062132/6c97fb84-21c6-11e7-95a5-2c638cfb649d.png)

**Comment by vanitasvitae** [comment]
I think I would remove the word "shared" and also the "(#dandelion)".

Edit: So only "via dandelion* client"

**Comment by gsantner** [comment]
The reason behind the hashtag is, that we have a little feedback how much posts are shared on which pods using our client, thats why I want to keep it.

**Comment by vanitasvitae** [comment]
but it also makes it hard to find posts actually related to dandelion :/ Maybe we need a new hashtag?

**Comment by gsantner** [comment]
We already got "#dandeliondev" ;)

**Comment by vanitasvitae** [comment]
In the screenshot it looks like the hashtag has not been recognized and made into a link

**Comment by gsantner** [comment]
Ehm, correct. Replaced with a slash.

**Comment by vanitasvitae** [comment]
>We already got "#dandeliondev" ;)

Yes, but I doubt that a new user will use that hashtag to blog about the app.
Also I believe that with the new signature, posts will appear as mentioned to the dandelion account. Isn't that enough feedback?

**Comment by gsantner** [comment]
No, we don't receive a "mentioned"-signal that way.

**Comment by vanitasvitae** [comment]
shouldn't that work theoretically?

**Comment by gsantner** [comment]
Ah. just found out how that works. gonna try that.  
The thing is, do we want that, to get notified about any single article in the network? With a hashtag we just can get a little overview of what gets posted. With a mention cannot get a overview whats posted, but get a notification for every single post

**Comment by vanitasvitae** [comment]
That notification thingy is a little shady I admit :D 
A hashtag would be nicer... but I wouldn't use #dandelion for that.
Maybe something like #dandelìon ?

**Comment by gsantner** [comment]
The thing is, #dandelion is used a lot already, I think it's hard to get away from it :D. But we can start now.
#dandelionpost #dandelion-post?

**Comment by vanitasvitae** [comment]
>#dandelionpost ?

A bit long isn't it? The thing about `#dandelíon` is that it looks nearly identically to `#dandelion` (note the í), so it still tells a (potential new) user that a post was made using dandelion.

**Comment by gsantner** [comment]
Maybe long, but it makes clear that this a post shared by dandelion :D For me both are okay.
