### ISSUE TITLE
Native tor/orbot support via NetCipher

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#16]
Hi!
It would be great to have native support for the usage of orbot as proxy, maybe proxy settings in general.
NetCipher is a library by the guardianproject that provides such functionality. Do you think it would be worth to implement this into the app?

**Comment by gsantner** [comment]
Thats something we can do, and I would personally like, but other things are more important/got an higher priority right now.

**Comment by vanitasvitae** [comment]
I have looked into this and it seems pretty much impossible using Android's standard WebView.
I asked the devs of NetCipher (the GuardianProject) if there is a way to enable proxy for WebViews on Android 6 and they replied that it is not possible. They recommend to use Mozilla's gecko engine, but I guess that would be too much work for this project (?).

**Comment by gsantner** [comment]
@vanitasvitae Different engine is definitely not the way to go, right. Maybe lets take a look how other projects resolve this.  
Here is for example the webTube project which supports Tor:
https://github.com/martykan/webTube
https://github.com/martykan/webTube/blob/master/app/src/main/java/cz/martykan/webtube/TorHelper.java

**Comment by vanitasvitae** [comment]
I'm making some progress on this. Proxying is working, I just made a mistake earlier. I do have some problems, but it's coming together.

**Comment by gsantner** [comment]
@vanitasvitae 👍

**Comment by vanitasvitae** [comment]
An interesting problem that I encounter is, that the WebView doesn't open .onion addresses for pods hosted on hidden services. Instead an external browser app opens when I do webView.loadUrl("xyz.onion");
I need to dig deeper into this later.
