### ISSUE TITLE
Provide screenshots with FDroid

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#161]
#### General information
FDroid's latest update allows apps to include screenshots as well as localized description texts.
That would be a nice addition!
https://forum.f-droid.org/t/new-ui-ux-of-f-droid-app/260/14

**Comment by gsantner** [comment]
I also already thought about it. I think we should first wait a little, so we can see how everything is displayed in the F-Droid client. Currently there is not much to see, and I think the format is not final. Let's postpone this until some apps got it already and there is a new iteration of the client out
