### ISSUE TITLE
click on the link crash app

### ISSUE THREAD

**Issue by jacouzy** [gsantner/dandelion#167]
#### General information

* **Android Device:6
* **Android API Version:** 
* **App version:1.0.2(22)
* **App source:**
* **Pod version:**

#### Steps to reproduce

1. Click on the link
2. The app crash
3. …

#### Expected result
**What is the expected output?** 

**What do you see instead?**

Upload screenshots via drag&drop if needed and apply resizing:
`<img width="30%" height="30%" src="https://cloud.githubusercontent.com/assets/67..b55.jpg">`

#### Debug output

Please post the output of adb logcat. The log should begin with the start of dandelion* and include all the steps it takes to reproduce the problem.
IMPORTANT: In-App debug log must be activated and the app restarted first!

````
adb logcat -s com.github.dfa.diaspora_android
````

#### In-App debug log

This is useful for visual bugs without application crashes

````
You can long click on the in-app debug log in order to copy it to the clipboard
````

**Comment by gsantner** [comment]
Thanks for reporting, but this is already fixed.
... see and comment on #164
