### ISSUE TITLE
Trouble uploading photos

### ISSUE THREAD

**Issue by ghost** [gsantner/dandelion#168]
#### General information

* **Android Device:**
4.1
* **App version:**
1.0.2

#### Steps to reproduce

1. Press pencil button
2. Press camera button
3. Tap photo to upload
4. Nothing happens

I don't know much about intents so I'm not sure if this relates to the "share" issue but it seems similar.

**Comment by vanitasvitae** [comment]
#11 is unrelated to this. This is probably a bug in the webview.

**Comment by gsantner** [comment]
Please provide more information, you did skip some parts of the issue template. Especially the pod version part. I cannot reproduce that problem on any device, and  would too suggest that it is a bug in your webview implementation. 

BTW: 4.1? That is API16. Our lowest supported version is 17. That means you use an special version which is explicitly said to gain no support.

**Comment by gsantner** [comment]
v1.0.2 also means you lowered the minSdk yourself and installed the git version then. v1.0.2 was never released for devices < 4.2

**Comment by ghost** [comment]
Android 4.4.2. It's a funky Chinese Android ROM. Not sure what's what. (No locale problems or anything-- I'm not a scientist.)

Dandelion was installed straight from F-Droid. It is now 1.0.3.

Pod is wk3.org so I imagine it's using the latest diaspora version. There was no quick access to data on the pod from dandelion and I'm under duress from other things so w/e

**Comment by gsantner** [comment]
Okay, so its not an outdated as suggested in description. But I think you still answered the issue with "funky chinese rom". The WebView implementation may just suck on that device

**Comment by ghost** [comment]
Yeah, dandelion seems to work fine on another device. Can upload photos. Weird.
