### ISSUE TITLE
Languages missing in the list in dandelion* 1.0.4

### ISSUE THREAD

**Issue by asereze** [gsantner/dandelion#169]
There are only 12 languages in the new version's language list (opoc/langpref): English, German, Spanish, French, Russian, Italian, Japanese, Polish, Dutch, Hungarian, Czech and Swedish. The new translations are missing.

**Comment by gsantner** [comment]
<https://github.com/Diaspora-for-Android/dandelion/commit/184de1931eca54f6ff9ba21e366630db88dfa7b9>
