### ISSUE TITLE
Add bookmark feature

### ISSUE THREAD

**Issue by gsantner** [gsantner/dandelion#171]
To resolve this add some kind of bookmark feature to the app. This means a list of items to be stored in appdata/preferences, which should be shown in a Bookmark fragment.  The first part is about to add this for URLs. So when a URL is opened in the webview and the bookmark button is clicked, this gets added/removed from the list. In the bookmark fragment there should be an option to remove existing items from the list.

The bookmark fragment can be based on the code of e.g. TagListFragment.

Should not be too hard ;)

**Comment by gsantner** [comment]
If you need more information ask. This issue is an idea, and about people to start contributing to the project. It has not much information because I pasted many ideas/issues and just let them out at the same time :). If you are interested in working on this, and have questions I can give you more details on this.

Register on https://hacktoberfest.digitalocean.com/, send a PR to fix this and get your t-shirt for free (4 accepted PRs to same or different GitHub repositories needed)  :). You have to mention the issue number in the commit/PR (e.g. `fix #20` / `about #8`) Find more hacktober issues from my projects: <https://github.com/search?&q=label%3Ahacktoberfest+user%3Agsantner>

**Comment by xc3p7n3** [comment]
I would like to work on this issue ..

**Comment by gsantner** [comment]
go for it 👍 😎

**Comment by vish21** [comment]
Hey I would like to work on this. Can you tell me you are asking for a new class to be implemented or specific class or folder where you want the changes?

**Comment by gsantner** [comment]
First of all: You need to know diaspora a little and have an account. You cant develop on it without a little knowlwdge of what this all is about.

Yes, new classes and interface, so backend and frontend. This most likely happen in the folder where fragments are.

**Comment by gsantner** [comment]
Sharing URLs to note keeping apps (like Markor) works fine and not requires changes to this app.
