### ISSUE TITLE
Mension of user

### ISSUE THREAD

**Issue by mama21mama** [gsantner/dandelion#178]
I want to mention a user in the following way

@diaspora

And has no effect...it doesn't work

Dandelion 1.0.6 (26)
Android 5.1.1
Pod: joindiaspora.com

* **App version:** 
* **System:** 
* **Pod:**

#### Description
What this is about, what happens and how. What needs to be done for it to happen.

**Comment by vanitasvitae** [comment]
You should report this to the diaspora repo, since it is actually a bug in the mobile interface of diaspora.

To work around it in dandelion, switch to the desktop site :)

**Comment by dud225** [comment]
Just as a side note, here is the bug report on Diaspora : https://github.com/diaspora/diaspora/issues/4817
