### ISSUE TITLE
image nav carrot partially hidden by '+' button

### ISSUE THREAD

**Issue by teslasmoustache** [gsantner/dandelion#18]
![screenshot_2016-05-22-16-29-30](https://cloud.githubusercontent.com/assets/3111759/15456779/60be8c5c-2040-11e6-8038-b9ba983d852f.png)

Perhaps this could be resolved by moving the carrots closer to the center?

**Comment by gsantner** [comment]
Duplicate of #4 .
I'm not sure if we really need the FloatingActionButton, for me it is somewhat bad in terms of usabitility in this app. I'm currently busy and won't push commits, but we are always open for contributions
