### ISSUE TITLE
Pod List

### ISSUE THREAD

**Issue by h3rb3rn** [gsantner/dandelion#181]
I'm Thema Podmin from https://dorf-post.de

In your fantastic App ist the outdated Link to my Pod. It is possible to login with your App, but in the Menubar is a Warning when you follow the old Link with a automatic refresh to the new address https://dorf-post.de

On the podupti.me ist the true Link to my Pod. Please refresh the Address anderen remove the diaspora from dorf-post.de Link in your Database.

#### General information

* **App version:** 
* **System:** 
* **Pod:**

#### Description
What this is about, what happens and how. What needs to be done for it to happen.

**Comment by gsantner** [comment]
Please send a PR with correct details. Edit here: <https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/res/raw/podlist.json#L249>

**Comment by gsantner** [comment]
Please send a PR with correct details. Edit here: <https://github.com/Diaspora-for-Android/dandelion/blob/master/app/src/main/res/raw/podlist.json#L249>
