### ISSUE TITLE
dandelion* 1.0.8 breaks Replicant 6.0

### ISSUE THREAD

**Issue by arielenter** [gsantner/dandelion#187]
#### General information
dandelion* 1.0.8
Andrid 6.0.1, Replicant 6.0, Galaxy S2 I9100

#### Description
When dandelion* 1.0.8 is installed on replicant 6.0, many apps start crashing, including trebuchet, f-droid and com.android.settings.Settings. It is impossible to access the app list and the only way I found to recover is to uninstall it with the following adb command:

adb uninstall com.github.dfa.diaspora_android

Some times the phone restarts all together.

adb logcat -s com.github.dfa.diaspora_android doesn't seem to be giving away any info on the matter. I'm sending some info I got from CatLog app, hoping it will help to find out what seems to be the problem, and I'll be also opening a new issue on the replicant website.

Thank you.
[2018-02-05-16-00-32.txt](https://github.com/Diaspora-for-Android/dandelion/files/1700322/2018-02-05-16-00-32.txt)
[tombstones.zip](https://github.com/Diaspora-for-Android/dandelion/files/1700323/tombstones.zip)

**Comment by arielenter** [comment]
I should had said that this doesn't happen with the previous version 1.0.6 . Both from F-Droid. Thank you.

**Comment by gsantner** [comment]
Not sure, but maybe it's related to the used android buildtools version that was somewhat broken at the build time. I have in my mind that this happend with quite some apps with specific buildTools version - and read it especially on F-Droid irc/forums.

**Comment by gsantner** [comment]
BTW, if an app can crash your whole system (and that completly unintentionally) this should also be the signal for you that your device is not safe. If I can create this, a bad guy can do this too and may do not friendly things. just a note, and something to think about.

**Comment by arielenter** [comment]
Thanks @gsantner , I'll wait and see if the guys from replicant can tell me if it's just a problem of my phone or it affects all replicant phones.

**Comment by gsantner** [comment]
I did push a new release today. If you have Android Studio installed / SDK+Java you should be able to test it already out. Otherwise, you have to wait quite some time, because F-Droid's queue is currently quite full.

**Comment by arielenter** [comment]
It seems this issue is not only affecting dandelion* 1.0.8, Conversations 1.23.4 is giving the same problem. I fear this might be affecting all newest builds on f-droid. I just opened a ticket on f-dorid: https://gitlab.com/fdroid/fdroidclient/issues/1321

Also, this is the ticket on Replicant just in case you want to follow the conversation: https://redmine.replicant.us/issues/1872

Thank you.

**Comment by gsantner** [comment]
Can you give latest memetastic version a try?

**Comment by arielenter** [comment]
I'll try, but I'm not sure I'll be able to compile it since I have never used Android Studio, but surely it shouldn't be so difficult.

Also it seems that the problem has been addressed before in the following ticket: https://gitlab.com/fdroid/fdroiddata/issues/979

**Comment by gsantner** [comment]
memetastic's latest apk is available since today on mainline fdroid repo, no need to compile

yeah, thats exactly what I wanted to point at. I knew there was something like this around.

**Comment by arielenter** [comment]
Oh, sorry I didn't know what you meant with memetastic. I'll give it a try C:

**Comment by arielenter** [comment]
I just installed memetastic. I didn't have any issue with it. Hopefully that means next dandelion* f-droid's build will come out clean. Thank you.
