### ISSUE TITLE
App crashes after clicking on contacts/personal settings

### ISSUE THREAD

**Issue by onos1** [gsantner/dandelion#193]
#### Expected behavior
After clicking on contacts, I was expecting another page to show  to manage my contacts. 

#### Actual behavior
Immediately I clicked on contacts the app crashes 

#### How to reproduce
download app [here](https://f-droid.org/repository/browse/?fdid=com.github.dfa.diaspora_android)
- click menu by tapping the three lines at the top left corner 
- click on settings
- scroll down and look for contacts
- click it
App crashes! 

* Mobile: Infinix note 4
* Operating system: Android 7.0
* version: 1.1.2

#### Recording Of The Bug
https://youtu.be/VYVESrjM4o0

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/app-crashes-after-clicking-on-contracts">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gsantner** [comment]
It crashes in this case because you don't have selected any pod yet, as said in the header, these settings are for pods. This should be just one line of code to fix, so please send a PR if needed.

**Comment by tobias-g1** [comment]
As I saw you grouped both of those crashes together I believe you should also add manage hashtags to this particular issue as the manage hashtags option also crashes using similar steps as provided above. 

Application Version: 1.1.2
Operating system: Android 5.0.2
Device: Samsung Galaxy Alpha
Model Number: SM-G850

I've kept this brief as I think it's clear based on the information provided, but if you need any more information I'd be happy to help.

**Comment by onos1** [comment]
Yeah crashes on Android 7.0 also you can get details [here](https://steemit.com/utopian-io/@onos/manage-hashtags-crashes-app-in-dandelion-app)

**Comment by gsantner** [comment]
They do the very the exact same, just instead of "/contacts" something like "/settings" in the loaded browser url.
