### ISSUE TITLE
Cannot switch to stream after displaying tags

### ISSUE THREAD

**Issue by oe1rsa** [gsantner/dandelion#198]
#### General information

* **App version: 1.1.3 (32)** 
* **System: Android 6.0.1 FP2** 
* **Pod: https://diaspora.kapper.net**
* **Language: German**

#### Description
After opening (starting the app) the stream is displayed. Using the "hamburger" menue, opening e.g. tags displays tags. Again using the "hamburger" cannot switch to stream, profile, activities.

**Comment by gsantner** [comment]
Hi those are the 2 things that are probably most used in the app, which I use a lot too. Nobody has reported that yet, and did not occur here on any device. 
Means - no logs, nothing can be fixed.

**Comment by oe1rsa** [comment]
Yes, the back button takes me back through a sequence of white screens until I am asked if I want to stop the app. Btw. the behaviour feels like it is not communicating with the network, because normally I see a small green progress bar on top, which is missing after the "white screens" have been triggered.

**Comment by oe1rsa** [comment]
#### Log
 Log created with 

pidcat com.github.dfa.diaspora_android > oe1rsa.log

I first killed the app from system settings and then
1) started -> stream visible
2) switched to tags -> tags visible
3) switched to stream -> white screen
4) used the back button -> tags visible
5) used the back button twice -> two white screens
6) prompted to end -> pressed ok

[oe1rsa.log](https://github.com/gsantner/dandelion/files/2172849/oe1rsa.log)

**Comment by oe1rsa** [comment]
Hmm, as already has been noted: I am seemingly the only one experiencing the "bug". So what is different for me: I do not use google play store and I have not activated google play services. Could that be the cause of the problems?

**Comment by vanitasvitae** [comment]
Very unlikely. Dandelion was designed with such a setup in mind.

**Comment by oe1rsa** [comment]
Is there any useful information in the log file? I mean there are some indications of errors, but since I am not skilled in Android development they do not make much sense for me.

**Comment by vanitasvitae** [comment]
I cannot spot any helpful errors in there unfortunately :(

**Comment by gsantner** [comment]
me neither

**Comment by gsantner** [comment]
I think this is again related to the over 2 years old android + supportlibrary bug that is still not fixed.....

<https://issuetracker.google.com/issues?q=fragment%20white> , <https://issuetracker.google.com/issues/37120406> ,  <https://issuetracker.google.com/issues/37118105#makechanges>

**Comment by oe1rsa** [comment]
Cool, works now without problems! Thank you for fixing although there were not many having the issue!
