### ISSUE TITLE
Build generates an invalid APK

### ISSUE THREAD

**Issue by ghost** [gsantner/dandelion#2]
Either building it from source or using the APK from your release page generates a broken APK. Running `./android-sdk-linux/build-tools/23.0.2/aapt dump badging ./Diaspora_v1.2.apk` throws up on

```
application: label='Diaspora' icon='res/drawable-mdpi-v4/ic_launcher.png'
launchable-activity: name='de.baumann.diaspora.SplashActivity'  label='Diaspora' icon=''
ERROR getting 'android:label' attribute: attribute is not a string value
```

**Comment by gsantner** [comment]
I created an PR regarding this issue. See PR#3.  
There were multiple strings that were in values-w820p/strings.xml that were not in the main strings.xml.  
The build worked fine for me please recheck after the commit is merged.

**Comment by ghost** [comment]
Commit is merged. Will make a new release this day. Thanks to both of you. @krt16s for your patience and @de-live-gdev for your hard work.

**Comment by de-live-gdev** [comment]
I accidentally mentioned the wrong Issue No in the PR commit, I meant this one. :D
I read the closed #1 issue, and I actually think that the was how the issue was solved created this issue. Ignoring build errors rather solving it is not the way to go ;).
Thankd  @scoute-dich for instantly merging

**Comment by gsantner** [comment]
I accidentally mentioned the wrong Issue No in the PR commit, I meant this one. :D
I read the closed #1 issue, and I actually think that the way how the issue was resolved did create this issue. Ignoring build errors rather solving it is not the way to go ;).
Thanks @scoute-dich for instantly merging

**Comment by ghost** [comment]
now released v1.3, only changes:
- updated changelog dialog
- updated changlog github site
- changed size off app-icon in header

Thanks again. I hope "Diaspora" will land on F-Droid in near future...

**Comment by gsantner** [comment]
Yeah, getting into the official repo needs some time..^^

**Comment by ghost** [comment]
Works on my local machine, thanks for the quick response.

Ref: https://gitlab.com/fdroid/fdroiddata/commit/021ef104d3454d76ff01db07d62dca18f986a309

**Comment by gsantner** [comment]
Hi @krt16s ,
sorry for disturbing you again.

We ( @scoute-dich @martinchodev and me) created an organization and finally come together to work on this app.  
The package name, versionName and versionCode has changed.  
Can you please remove the builds, or link to the new one from this 2 apps:  
(by @martinchodev  )https://f-droid.org/repository/browse/?fdfilter=diaspora&fdid=ar.com.tristeslostrestigres.diasporanativewebapp  

(by @scoute-dich ) https://f-droid.org/repository/browse/?fdfilter=diaspora&fdid=de.baumann.diaspora  

I can send the commit and supply metadata on GitLab if you want. Please contact us if you got any questions. Thanks :D

**Comment by ghost** [comment]
Added comment in the new ticket #5.
