### ISSUE TITLE
Dandelion opens diaspora internal links in an external web browser

### ISSUE THREAD

**Issue by Ravenbird** [gsantner/dandelion#202]
#### General information

* **App version:** 1.2.0 (33)
* **System:** Android 7.0 Patchlevel 08.08.2018
* **Device:** Samsung Galaxy Tab S2 WiFi (SM T-813)
* **Pod:** https://diaspora.town

#### Description

When I want to open a diaspora internal link (for example another user's profile) in Dandelion, it is opened in an external webbroser instead of in Dandelion.

**Comment by gsantner** [comment]
your pod is diaspora.town . which link did you want to open?

It is intentional that everything not being a link to something your pod is counted as external.

**Comment by Ravenbird** [comment]
I don't know what the problem was. After I had re-installed the tablet and also Dandelion it went now. So as far as I can judge it so false alarm. I'm sorry

**Comment by gsantner** [comment]
no problem
