### ISSUE TITLE
[Feature Request] Auto-collapse long text posts, auto-expand image posts

### ISSUE THREAD

**Issue by knobhead** [gsantner/dandelion#213]
Hi, thanks for this nice and nifty diaspora* client!

(I tried searching for similar issues but to no avail. If I dig out old corpses here, let me know. )

#### General information

* **App version:** 1.2.2 fdroid
* **System:** Android 7, LineageOS 14.1
* **Pod:** joindiaspora.com

#### Description
Some people and especially many RSS-AutoPoster-Bots post full articles to d*. While this is nice because you don't have to leave the app/the platform to read articles, this means an awful lot of scrolling within the app. 
Could you include a feature that automatically collapses too long text postings and hides the rest behind an "read more" button? This would give us the chance to decide if a post is interesting enough to fully read it / scroll through it.

Many picture posts, on the other hand, already do show a "read more" button (wording similar), but just expand a tiny bit on tap and show the rest of the picture. I'd love to have them auto-expanded on posting-load.

I hope I could express my wish understandable. If you have any questions or need some sketches, let me know. I'll be happy to contribute, just can't help with code here.

**Comment by gsantner** [comment]
Please ask at diaspora itself for mobile client changes. They do have the code (from desktop version) but its not available/ported to mobile layout.

**Comment by knobhead** [comment]
Too bad. Thanks for letting me know, [did so](https://github.com/diaspora/diaspora/issues/7880).
Keep up the good work, @gsantner !
