### ISSUE TITLE
Ignores "Default aspects selected for posting"

### ISSUE THREAD

**Issue by alexs77** [gsantner/dandelion#216]
#### General information

* **App version:** 1.2.1 F-Droid
* **System:** Huawei P20 Pro, Android 8.1.0, Stock OS (from Huawei, no root, no mods)
* **Pod:** pluspora.com

#### Description

On the web, in Settings -> Account, I set the "Default aspects selected for posting" to "Public". But when I create a new post in dandelion, the "public settings" for this post are set to "All aspects", not "public".

**Comment by alexs77** [comment]
That's https://github.com/diaspora/diaspora/issues/7333, I suppose?

**Comment by gsantner** [comment]
looks like yes
