### ISSUE TITLE
hide bottom panel 

### ISSUE THREAD

**Issue by moshpirit** [gsantner/dandelion#22]
The app looks delightful, it's really cool, thanks for that, but sadly, the bottom app needs too much space and would be very nice if the bottom panel automatically got hidden when we scrolled down and showed up again when we scrolled up or open a new link.

**Comment by gsantner** [comment]
First of all: **Use and fill out the provided  issue template.**

There are 2 bars, the top goes away automatically after little scroll. It's the same amount space than as in versions before, and like in any other app.

I tried that auto-hide also on bottom, but there are many things that break when bottom auto-hide is enabled. From toolbar jumping over webview, to a non working keyboard, or crashes on older android versions. 

My personal opinion: These are the **most needed actions** in the app. Should always be visible.
If somone does implement an working solution (PR's welcome) I'm okay with that. A working solution should have an option to switch between intelli-hide and always show.

**Comment by vanitasvitae** [comment]
We already had that idea. We're discussing that.

**Comment by gsantner** [comment]
I lowered the bottom toolbar, now it's using less space. I also tried to make it auto-hide but it's not possible that easily. I won't make changes and invest time here anymore.

<img src="https://cloud.githubusercontent.com/assets/6735650/15857085/bd549396-2cb9-11e6-96d4-f200dd018b6e.jpg" height="30%" width="30%">

**Comment by vanitasvitae** [comment]
This is targeted in #29

**Comment by vanitasvitae** [comment]
This is now implemented.
