### ISSUE TITLE
Disable refresh on pull down while editing a message

### ISSUE THREAD

**Issue by valvin1** [gsantner/dandelion#229]
#### General information

* **App version:** 1.2.5
* **System:** Android 7.1
* **Pod:** framasphere.org

#### Description

While positing a message it is possible to trigger a refresh on pull down which causes the loss of all the text entered.

Can we disable it on this action ?

Here is an example, in that case I triggered manually but when you've typed several lines it triggers itself while browsing your text : 

(edit  : remove bad video)

**Comment by gsantner** [comment]
thanks for reporting! No additional video needed, know whats meant.

@massimilianoLe
I guess this should be the matter of one `set(true/false)` call, right?

**Comment by massimilianoLe** [comment]
I'm on it. I already got it working on Nomad

**Comment by massimilianoLe** [comment]
@gsantner
Do you have a nice icon i can use for that option?

**Comment by massimilianoLe** [comment]
@gsantner
i already had a pull request that i forgot
https://github.com/gsantner/dandelion/pull/226
