### ISSUE TITLE
Next page HTML button partially hidden on activities stream

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#23]
In the main stream the button for loading the next stream page is high enough to be not overlapped by bottom bar. This is not the case in the activities stream which shows my own posts.

**Comment by vanitasvitae** [comment]
Strange, now it is o.O

**Comment by gsantner** [comment]
Bottom toolbar is not above (z-Index) webview. It's on the tail of it

**Comment by vanitasvitae** [comment]
This happens sometimes when the page has not finished loading while the WebView reaches the end of the page.
