### ISSUE TITLE
[Feature Request] shorten long post

### ISSUE THREAD

**Issue by valvin1** [gsantner/dandelion#230]
#### General information

* **App version:** 1.2.5
* **System:** Android 7.1
* **Pod:** Framasphere.org

#### Description

While seeing my timeline there are few messages which are very long. It would be great if that message was shorten (like on web interface) to 10 lines for example with "Read more" action to expand the complete message. At the moment when there is a long message which I don't want to read it is long to swipe to go to the next message.

**Comment by gsantner** [comment]
#213

**Comment by valvin1** [comment]
sorry i've not seen it ;-)
