### ISSUE TITLE
Inline textarea input makes writing difficult

### ISSUE THREAD

**Issue by RefurioAnachro** [gsantner/dandelion#234]
#### General information

* **App version:** 1.2.5
* **System:** android
* **Pod:** pluspora

#### Description

Imprecise fingering the keyboard leads to the content of edit boxes getting lost too easily. This can happen because the finger misses the vkeyboard. Or because one accidentally hits the "next field" button which sits right next to the space bar key, which causes the keyboard to disappear, after which your next keypress goes to some random active area instead, losing painstakingly entered content instead.

Suggested solution: make active edit boxes fullscreen, and remove the next-field key. Put the send button on top, far away from the keyboard.

**Comment by gsantner** [comment]
Please give feedback at diaspora* bug tracker to improve the mobile layout.
