### ISSUE TITLE
How to remove a draft?

### ISSUE THREAD

**Issue by RefurioAnachro** [gsantner/dandelion#235]
#### General information

* **App version:** 1.2.5
* **System:** android
* **Pod:** pluspora

#### Description

I thought I had lost the text I had just entered (for the 5th time or so), but now one of the pastes I did shows up ready to post (again), whenever I switch to the dandelion app! I extected to see the stream instead. Hitting send (and deleting the result) does not seem to get rid of it.

**Comment by gsantner** [comment]
dandelion is stateless beside cookies & cache. It does not store what you type by itself. If so this is a new diaspora feature I'm not aware of.

Please delete cache of the app, otherwise ask at diaspora bug tracker.
