### ISSUE TITLE
Multi-account support

### ISSUE THREAD

**Issue by ghost** [gsantner/dandelion#24]
Everything is in the title. A lot of people using diaspora tend to have multiple accounts on multiple pods. Would be nice to be able to switch between accounts in the same app.

**Comment by vanitasvitae** [comment]
Sorry that there was not so much feedback on your suggestion so far. We are discussing it internally. At the moment we settled on not adding too complicated features until the diaspora*-API is released. We have to rewrite most of the app anyways when it is released.

I heard you are actively working on the API. Can you estimate how long it will take until its usable?

**Comment by ghost** [comment]
> We have to rewrite most of the app anyways when it is released.

No, actually. Pod running versions prior 0.6 (at least) won't support API.

> I heard you are actively working on the API.

Not anymore. I don't think anybody is still working on it. I worked with someone on an OAuth 2/OpenID authentification/authorization mecanism. But there's nothing more. There's [a specification proposition](https://diaspora.github.io/api-documentation/), but that's it.

**Comment by vanitasvitae** [comment]
Well, thats unfortunate, but good to know. Thank you for that information :+1:

**Comment by ghost** [comment]
From what I see goin through the code, multi-account feature could be achieved by using a [`List<PodUserProfile>`](https://github.com/Diaspora-for-Android/diaspora-android/blob/master/app/src/main/java/com/github/dfa/diaspora_android/App.java#L24), right?

**Comment by gsantner** [comment]
@AugierLe42e Well, PodUserProfile just contains extracted data from the current session(like name, image, but NOT authentication,cookies)...I would say thats the easiest part. ;)
Theres also
- WebView, Cookies, Sync cookies
- SharedPreferences
- Methods using something of the 4 classes above (pretty much everything)

**Comment by ghost** [comment]
So I guess the first step is to unify everything into a `PodInstance` or something.

**Comment by vanitasvitae** [comment]
Unfortunately the whole app isn't in a very good state at the moment regarding modular design. But we're working on it. Splitting it up in more granular modules is probably the way to go. PRs are welcome :+1:

**Comment by ghost** [comment]
I'd really like to help, but I'm really not a Java fan. Especially Java 7. If the app had been written in Groovy or Kotlin, it would have been a pleasure to help :/

**Comment by gsantner** [comment]
Diaspora 0.6.0 is currently in progress. As it may contain breaking changes, lets definetly wait with this one.

**Comment by vanitasvitae** [comment]
Just being curious... What changes would be needed to implement this? Extracting and storing/restoring cookies of the single accounts? What else?

**Comment by gsantner** [comment]
**In short:  Pretty much every single file needs to be changed.**
- Saving/Loading multiple Preferences. (Whole SettingsActivity, everywhere AppSettings is used)
- Syncing multiple cookie stores from the webview (Saving/Reloading)
  - I'm afraid that cannot even work, because as far I remember it's an Singleton that can provide cookies for multiple pages, but not for one page twice (Correct me if I'm wrong)
  - Syncing cookies from the webview is deprecated (I already faced that.) See e.g. https://stackoverflow.com/questions/30502411/cookiesyncmanager-is-now-deprecated-what-can-i-use-instead. I'm not sure if we implement something using CookieSyncManager will work in current, future and older versions.
- When something is shared into the app, there must be a chooser to which account it should be shared to

> I'm personally against implementing this, because using WebView itself is already hacky, it needs a lot of changes and time, and will degrade code quality. 
> In short: Let's wait as the API gets more stable and feature complete, use the API and strip every single line related to WebView. Using an API can make this lots of easier, because we can directly save and send the token.
> BTW: I'm also using multiple accounts, I just have two differnt APK´s installed ;)

**Comment by vanitasvitae** [comment]
I think it depends, in which way we implement multi account usage. We could implement some kind of quick switch between accounts. The user may open the settings and there is a list of accounts with radio buttons where they can chose which account to use.
After clicking on one entry, the webview etc. loads the cookies of this account. 

I would not allow different settings for the accounts.

**Comment by gsantner** [comment]
Reread the comment 2 above, all of the points do also matter if there is a switch account option. Preferences: Shure there are multiple needed, as we store pod information in Preferences (but not Login credentials :+1:  )

**Comment by vanitasvitae** [comment]
We could further encapsulate pod settings. (There is/was a podSettings object somewhere. We could arrange multiple of these.

**Comment by ghost** [comment]
> Preferences: Shure there are multiple needed, as we store pod information in Preferences (but not Login credentials :+1: )

Not really. You could use a singleton object that serializes/deserializes to/from JSON using Jackson, for instance, and handle a list of preferences models.

**Comment by gsantner** [comment]
@AugierLe42e @vanitasvitae 
Sure. We can change the data model for the account, but this does **NOT** resolve the main issues regarding the webview and how to handle cookies..
Read/Write of JSON should be the easiest part if its done this way. It can be JSON, XML, Preferences, doesn't matter, all of these allow multiple accounts. But the app is written to accept **one** account.

**Comment by vanitasvitae** [comment]
Bookmark: https://stackoverflow.com/questions/26323050/how-to-achieve-multi-login-for-webviews-in-android

**Comment by ghost** [comment]
Can't you try to inherit `CookieManager`? The class is not final.
**Edit:** NVM, the class _is_ final. It's just not indicated in the documentation.

**Comment by gsantner** [comment]
For a proper implementation we have to wait for methods in the diaspora API allowing this.

**Comment by ghost** [comment]
You are going to wait a long time :/
An API on diaspora is no trivial thing.

**Comment by gsantner** [comment]
@AugierLe42e Thats because it seems like a very low priority for the devs (not blaming anyone, nice work for nice stuff, for free). Without a good API there can't be good mobile clients, and android/iOS is a huge market. Well, and without a good mobile app, or at least a good/useable mobile view, you can't really invite friends or family to join diaspora...Not everybody has a computer. The current state of the app, using webview is a slow workaround, not the solution. I hope the diaspora* devs realize at some day how much important the API is, and focus on it.

**Comment by gsantner** [comment]
Hey everybody!
I have some news on this.
While still there is no useable API or like that, I choose a different way for a basic solution to this.
I added another flavor called `dandelior*` with a different id and icon, that you can install beside normal dandelion. You can use that than as second account/app just like secondlion was in the past.
The big difference here is that this goes same versioning like dandelion, and that I will try to get into F-Droid with the dandelior, I hope/think the team is going to understand the problem. Diaspora users often demand this, but I don't see a different way to resolve this currently.

**Comment by gsantner** [comment]
After so many years yes there is finally a API, however I barely use diaspora anymore. I don't think that dandelion will be ever rewritten to use the API - it would basically be a complete new codebase. Something I don't consider to do myself.

The API just came out or got it's expected feature set many years too late and cooperation for such mobile apps was back then not really wanted by the diaspora team.
