### ISSUE TITLE
Accessing dandelion through a decentralized slow dns tunnel with the proxy option like vpnoverdns port  8081 on Android was not successful 2019/03/19.

### ISSUE THREAD

**Issue by Tech1evolve** [gsantner/dandelion#241]
#### General information

* **App version:1.3.0 
* **System:Android
* **Pod:**

**Comment by Tech1evolve** [comment]
It could be vpnoverdns functions are not activated for the Android version or the Android itself is not activated.

**Comment by Tech1evolve** [comment]
Anxiety avoiding, vpnoverdns is not affiliated with me(end user), disclaimer.

**Comment by gsantner** [comment]
Hi!

I'm feeling like I can't help to debug or fix your problem, sorry! :D

**Comment by Tech1evolve** [comment]
Dandelion.apk through Proxy server pro.apk then vpnoverdns to the free slow internet.
Functioned

**Comment by Tech1evolve** [comment]
When the network is really slow the dandelion apk times out and vpnoverdns.apk is still collecting bytes .

**Comment by Tech1evolve** [comment]
When the proxy server pro connection timeout is raised to 300 ,  even slow internet dandelions porn is accessable.

**Comment by Tech1evolve** [comment]
Thank you, great application
