### ISSUE TITLE
Use the new diaspora* API

### ISSUE THREAD

**Issue by Flaburgan** [gsantner/dandelion#246]
I'm opening this issue because the diaspora* API made huge progress thanks to @hankg. https://github.com/diaspora/diaspora/pull/7462 is now tagged to be included in the next major release of diaspora*. Thanks to @jhass the CI is now green, I guess the code will make its way to the `develop` branch in the coming weeks.

Dandelion is the first project I thought about when I was wondering who will want to use it so I wanted to tell you those progress. I'm running the bleeding edge diaspora* code on https://diaspora-fr.org so I will immediately pull the API code once merged. Feel free to open an account there for testing purpose.

As a reminder, the API documentation is available at https://diaspora.github.io/api-documentation/index.html

I guess this is going to open a whole new world for dandelion :smile:

**Comment by gsantner** [comment]
Hi!

thanks for comment. Nice to hear that API gets available soon.
As off implementing API, I would suggest to start off from a fresh project and copy over code parts where required. The current code base is really much centered onto webview. If starts on it, I happily rename/change this to dandelion-legacy, or name the new one e.g. dandelion neo..or like this :D.

**Comment by frankrousseau** [comment]
Great news!

**Comment by Flaburgan** [comment]
It took more time than expected, but the API is now merged into develop! 

Read more about it there: web+diaspora://hq@pod.diaspora.software/post/707634201f9501387f3d5254001bd39e ([fallback link](https://diaspora-fr.org/posts/707634201f9501387f3d5254001bd39e) if you didn't add the `web+diaspora` scheme from the settings of your pod)

**Comment by gsantner** [comment]
After so many years yes there is finally a API, however I barely use diaspora anymore. I don't think that dandelion will be ever rewritten to use the API - it would basically be a complete new codebase. Something I don't consider to do myself.

**Comment by gsantner** [comment]
After so many years yes there is finally a API, however I barely use diaspora anymore. I don't think that dandelion will be ever rewritten to use the API - it would basically be a complete new codebase. Something I don't consider to do myself.

The API just came out or got it's expected feature set many years too late and cooperation for such mobile apps was back then not really wanted by the diaspora team.
