### ISSUE TITLE
Make 'swipe-down-to-refresh' cancelable by swiping back up

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#28]
#### General information
- **Device:** doesn't matter
- **Android Version:** doesn't matter
- **Pod:** doesn't matter
- **Diaspora pod version:** doesn't matter
- **App source:** doesn't matter
- **App version:** HEAD

I have:
- [x] searched open and closed issues for duplicates
- [x] Diaspora for Android installed with an version >= 0.1.1
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce
1. Open app
2. On top of the stream swipe down but don't lift the finger
3. Swipe back up in the same movement
#### Expected result

Expected: No refresh, swiping back up indicates that the user does not want to refresh.

Actual result: Site refreshes

**Comment by vanitasvitae** [comment]
I guess the buggy (too sensitive) behavior of the swiperefreshlayout is caused by a strange nesting of Layouts. We should rework this sometime.

**Comment by vanitasvitae** [comment]
Reopen due to insufficient resolution: Solution broke Animated Toolbars :/

**Comment by gsantner** [comment]
SwipeRefreshLayout was removed in https://github.com/Diaspora-for-Android/diaspora-android/commit/9ecf55ca8210e7e3c8a53745339f61ce44bf159b

**Comment by 4ndyD** [comment]
This was removed from the post editor where there shouldn't have been a swipe refresh at all, but the problem still exists in the stream.

**Comment by gsantner** [comment]
You don't have the latest version (master).
The swiping isn't anymore in the app.
So the bug related to the lib cannot exist.
