### ISSUE TITLE
feat: Support sharing with multiple aspects

### ISSUE THREAD

**Issue by Tyler-2** [gsantner/dandelion#282]
#### General information

* **App version:** 1.3.5
* **System:** Android
* **Pod:** Any

#### Description
The dialog to select which pod to share with only allows one selection. Diaspora through the web interface allows you to select multiple aspects. For instance Friends, Family.

Please support sharing with multiple aspects.

**Comment by gsantner** [comment]
dandelion IS USING the web interface, in the mobile view mode.

As that is specific question to mobile diaspora view, please ask at diaspora.
