### ISSUE TITLE
'Back to top'-button does not set swipe velocity to 0

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#34]
#### General information
- **Device:** doesn't matter
- **Android Version:** doesn't matter
- **Pod:** doesn't matter
- **Diaspora pod version:** doesn't matter
- **App source:** doesn't matter
- **App version:** v0.1.3

I have:
- [x] searched open and closed issues for duplicates
- [x] Diaspora for Android installed with an version >= 0.1.1
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce
1. Open stream
2. Fast swipe up to go deeper in the stream (let the stream scroll on itself)
3. Click 'back-to-top'-button to go back to the top of the stream while the stream is still scrolling
#### Expected result

Stream goes to top and stops there

What is the expected output? What do you see instead?
Stream "bounces" off the top and scrolls down again on its own
I guess this is caused by the button not setting velocity to 0, so there is still velocity left when the top is reached.

**Comment by gsantner** [comment]
SwipeRefreshLayout was removed in https://github.com/Diaspora-for-Android/diaspora-android/commit/9ecf55ca8210e7e3c8a53745339f61ce44bf159b
