### ISSUE TITLE
Ask for storage permission when sharing images to other apps

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#35]
#### General information
- **Device:** doesn't matter
- **Android Version:** doesn't matter
- **Pod:** doesn't matter
- **Diaspora pod version:** doesn't matter
- **App source:** doesn't matter
- **App version:** HEAD

I have:
- [x] searched open and closed issues for duplicates
- [x] Diaspora for Android installed with an version >= 0.1.1
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce
1. Fresh installation of Diaspora for Android
2. Share image to other app (eg. Telegram)
#### Expected result

Expected: App asks for storage access permission to save Image and share it afterwards.

Actual result: App does not ask for permission. Sharing fails.

**Comment by gsantner** [comment]
Already implemented
