### ISSUE TITLE
Answer button in conversation view

### ISSUE THREAD

**Issue by jonsger** [gsantner/dandelion#4]
If I open a message, write some stuff and want to click the answer button. Its covered by the "x" menu button. 
V1.3 under Android 5.0.2
![tmp_6402-screenshot_2016-03-23-22-04-54-1209398048](https://cloud.githubusercontent.com/assets/3876790/14000883/8d7e82f0-f143-11e5-8035-d49e4bca7268.png)

**Comment by ghost** [comment]
Ok, will look on it in at the weekend.

**Comment by ghost** [comment]
I already implemented a working method to hide fab-buttons every time the keyboard pops up...

**Comment by ghost** [comment]
Anyone tested? Except me?

**Comment by gsantner** [comment]
Whats the status about this?
I'm not sure if we really need the FloatingActionButton, for me it is somewhat bad in terms of usabitility in this app.

**Comment by gsantner** [comment]
@jonsger d60069253e3fd61bf45688b4ef41e3f853d1c3a1  removed the '+' FAB-Button. Replaced by a toolbar. This makes your issue obsolete/resolved.
