### ISSUE TITLE
[META] Design, UI, Artwork, Colors & Branding

### ISSUE THREAD

**Issue by gsantner** [gsantner/dandelion#40]
This issue is an ongoing issue about the app design, the colors and images.  
Submit ideas.  

Text below this line contains updated informations (Whats currently going on / What we are looking for)

---

New images needed:
The images should contain a blowball (Pusteblume)
- Splashscreen
- NavigationDrawer - Top image

**Comment by gsantner** [comment]
Currently the primary grey color looks really unfriendly. I tried multiple variations, and found this soft green really nice. (Color: hex **608b6f**)
<img width="30%" height="30%" src="https://cloud.githubusercontent.com/assets/6735650/17276919/88c2b124-5736-11e6-9104-55742b486122.jpg">

**Comment by ghost** [comment]
Hi, (yeah I'm still alive) I like the light green. ;-)

**Comment by SansPseudoFix** [comment]
Not sure if it's the right place for it (if not, I will open a separate issue), but there is "branding" in the title, so...
I see many `Diaspora*` on translation's files, but actually, the correct way is `diaspora*` or `DIASPORA*`.

> diaspora\* can be used lower-cased or upper-cased but all the letters should be the same: diaspora\* is preferred, DIASPORA\* is valid, Diaspora\* or DiAsPoRa\* are not.

[See wiki](https://wiki.diasporafoundation.org/Branding).

**Comment by ghost** [comment]
Hi,

I have also some new suggestions.
- primary and accent color should be two colors with a good contrast (for example "Komplemantärfrarben), so that you differ them on the first look. The actual light green (statusbar) and the brown (progessbar) are very similar
- don't use more than two colors. The second color of the notification and messages icon in the statusbar should be the accent color.

This also stands in the Google color guidelines: https://material.google.com/style/color.html#color-color-schemes

I think if you follow this the ui will look more clean and modern. Hope this helps.

regards
Gaukler Faun

**Comment by gsantner** [comment]
Hi again @scoute-dich, :)

you are right, but I tried multiple variations of other colors and couln't find an color which would make it (the notification bell/message received) better. You can suggest colors, please attach Screenshots and the colors if you find something suitable. At least Purple, blue, oramge looks awful to me there in combination with the greenish titlebar.

**Comment by ghost** [comment]
I will do it the next days when I have more time.

**Comment by gsantner** [comment]
@SansPseudoFix We will make corrections regarding that all together. Requires some work in the translation platform and on the source files.

**Comment by gsantner** [comment]
I rethought the colors. The green is somewhat nice, but also makes somewhat sad.
Heres what I implemented now:

<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18399185/28ad8322-76d0-11e6-98c7-95d88accc451.jpg">
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18399184/288b412c-76d0-11e6-9e9c-97f8e69f1259.jpg">
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18399315/92768d30-76d0-11e6-9efd-e67a9948e344.jpg" >

@scoute-dich The Notification/Mail Icon now uses the accent color in activated state.

How do you guys like it?
@SansPseudoFix Changed the app name to "diaspora*"

**Comment by ghost** [comment]
Blue looks nice. but I still think, that the contrast between primary and accent color is to low. The implematär color of blue is orange. so i think you should use something in an orange color tone. Progressbar uses also accent color?

Shorter names are always better and more pregnant. So I think "diaspora*" would be also a good idea.

**Comment by gsantner** [comment]
@scoute-dich  You mean like in my Meme-Creator?
https://gsantner.gitlab.io/fdroid/memetastic/
Btw:  You meant "DE: prägnant" I know :D

<img src="https://gsantner.gitlab.io/fdroid/static/img/screens/at.san.ring.memecreator.android/out3.jpg" width="40%" height="40%" />

**Comment by ghost** [comment]
Yes and yes.  ;-)

**Comment by ghost** [comment]
I would also change the icon color to match the app colors. And one more design suggestion:

Remove the shadow from "diaspora" on the splashscreen. It's not good for readability. Less is often more. It looks more modern and professional. Here is the splashscreen for our school moodle app: 

<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/3949944/18401841/e0b6da20-76dc-11e6-82a0-4eaaa04e1c61.png" />

https://github.com/scoute-dich/HHSMoodle/blob/master/app/src/main/res/drawable-nodpi/splashscreen.png (The colors are not my choice -> the strange pink is our "school color").

I dont know if I have time next week, but I can try to make a splashscreen with your template.

Regards
Gaukler faun

**Comment by gsantner** [comment]
Icon color: where?

App icon: We just have the icons in png so we cant change it easily without degrading quality. A new svg would be great.

**Comment by ghost** [comment]
I can also make a svg icon, when I have the time.

Icon color: the blue gray background. Going to bed now. I think I will make it on Sun- or Monday.

**Comment by gsantner** [comment]
@scoute-dich Great! Theres another contributor interested on designing the new icon. I messaged you all together on diaspora\* because I couln't find him on github.

**Comment by vanitasvitae** [comment]
@gsantner I would remove the shadow on the diaspora\* writing in the splash screen (Material Design), and also put the writing a little higher up under the icon.

Are we going to use the proposed icon in the next release?

**Comment by gsantner** [comment]
@scoute-dich @vanitasvitae @SansPseudoFix  

Changes from today:
- splashscreen
- accent color (orange)
- progress bar
- (new) notification&message count badge icon

<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18418981/5a961caa-7851-11e6-8681-fa6527da981c.jpg">
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18418980/5a9254f8-7851-11e6-9b47-a56f3db5d852.jpg">

**Comment by ghost** [comment]
Yes now it's nearly perfect. Can you post the rgb code for primary and accent color? Then I make an svg icon with same colors. ; -)

**Comment by gsantner** [comment]
https://github.com/Diaspora-for-Android/diaspora-android/blob/master/app/src/main/res/values/color.xml

**Comment by ghost** [comment]
![blue_orange](https://cloud.githubusercontent.com/assets/3949944/18419363/35dec83c-7859-11e6-98f1-454d32603a6c.png)
![blue_white](https://cloud.githubusercontent.com/assets/3949944/18419365/35e3c27e-7859-11e6-91b0-30a60838b4a3.png)
![orange_blue](https://cloud.githubusercontent.com/assets/3949944/18419364/35e19dbe-7859-11e6-8144-9553eba5826c.png)
![orange_white](https://cloud.githubusercontent.com/assets/3949944/18419366/35e4659e-7859-11e6-9543-9afc2a54b5d3.png)

Icons with possible combinations. I prefer blue-orange (theme matching) or blue-white (looks best on splashscreen. My first choice would be blue-white. In the zip file is the svg-icon and a color palette for Inkscape  with all material colors (Don't know, if you have it already.).

Regards
Gaukler Faun

[icon.zip](https://github.com/Diaspora-for-Android/diaspora-android/files/466146/icon.zip)

**Comment by gsantner** [comment]
I personally dislike to have both of them in one icon.

As the icon is used in the splascreen, on the navigation slider (no avatar img), and on the android activity overview: The bar/area will always will be filled with primary color. So Orange and white is the best option in my opinion, because blue + anything would just show the star in those cases above.

**Comment by vanitasvitae** [comment]
I'm not really sure about the icons. Out of the four I'd prefere the blue one, but that will cause problems with the splash screen (all blue).

But I don't really like the orange one :/ remember, it represents a blowball...

**Comment by ghost** [comment]
Then what about orange white? On the splashscreen perhaps only the blowball, or what about no icon on the splashscreen? We have the blowball there already in "diaspora*".

**Comment by vanitasvitae** [comment]
I meant, maybe orange is not the best color to represent a blowball.

**Comment by gsantner** [comment]
As said above, orange + white would make no problems
By the way: This is my first app, where the app has to/should match the color palette.
It's no must.

**Comment by ghost** [comment]
@vanitasvitae 
You're right. Blue is a good primary color, since a blowball flies through the air. So I would definitly suggest to use the blue-white icon with following consequences:
- No icon on splashscreen an "diaspora*" a little bit bigger -> would be a clean, modern and simple splashscreen
- Image as header background
- on the android activity overview: we can not have everything...

**Comment by vanitasvitae** [comment]
Why not make the icon in a very sky-like light blue color? I mean the icon must not follow primary/secondary colors.

Edit: I'd suggest something like #67BEDB as icon background color and a white asterisk

**Comment by gsantner** [comment]
I rethought the issues I summed up above. I think it's a feature not a bug.
Lets keep the primary color as the background. Everywhere the icon will be used then, when the bg is also primary, just the White star is left over. which I think will be great.

BTW: @scoute-dich  The svg has some errors, it cannot be imported as android vector drawable..
Here is a fixed one:[Diaspora.svg.zip](https://github.com/Diaspora-for-Android/diaspora-android/files/466169/Diaspora.svg.zip)

**Comment by ghost** [comment]
The shadow is also left over ...

**Comment by gsantner** [comment]
Shadow: Removal was intentionally.
So this gets possible   Tadaa:
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18419846/668f57a2-7864-11e6-858e-720c79b746d7.png">
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18419847/668fa504-7864-11e6-9f1d-363efa68709f.png">
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18419862/a506e4f0-7864-11e6-9f35-ae140968cb4a.png">
<img width="30%" height="30%"  src="https://cloud.githubusercontent.com/assets/6735650/18419848/66904d74-7864-11e6-99b2-61d0b9af7bbc.png">

**Comment by vanitasvitae** [comment]
I'd make the asterisk a little bigger in size. So that it fits the name/pod in the drawer and is also a little bigger in the splashscreen

**Comment by gsantner** [comment]
Here is an more lighter color:
https://cloud.githubusercontent.com/assets/6735650/18419895/f4a43796-7865-11e6-940a-05fc37a98137.png
https://cloud.githubusercontent.com/assets/6735650/18419901/0ebc6086-7866-11e6-8064-63103263d903.png
https://cloud.githubusercontent.com/assets/6735650/18419896/f4a483d6-7865-11e6-8da2-eaaec78e285f.png
https://cloud.githubusercontent.com/assets/6735650/18419897/f4a64838-7865-11e6-95c6-2109b0503839.png

**Comment by vanitasvitae** [comment]
I'd go for a color in between. The darker one is a little too dark and the brighter one definitely to bright for my taste :)

Am 11. September 2016 21:23:43 MESZ, schrieb Gregor Santner notifications@github.com:

> Here is an more lighter color:
> ![screenshot-2016-09-11__21-22-01](https://cloud.githubusercontent.com/assets/6735650/18419895/f4a43796-7865-11e6-940a-05fc37a98137.png)
> ![Uploading screenshot-2016-09-11__21-22-09.png…]()
> ![screenshot-2016-09-11__21-22-27](https://cloud.githubusercontent.com/assets/6735650/18419896/f4a483d6-7865-11e6-8da2-eaaec78e285f.png)
> ![screenshot-2016-09-11__21-23-01](https://cloud.githubusercontent.com/assets/6735650/18419897/f4a64838-7865-11e6-95c6-2109b0503839.png)
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/40#issuecomment-246198855

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gsantner** [comment]
You said sky-like blue light :D

**Comment by vanitasvitae** [comment]
For the icon, not the whole app :D

**Comment by gsantner** [comment]
What about that one? 
It even matches the login button^^
I noticed, that I like it even more than the indigo one (overall, not just icon).
And btw: Enhances the "freedom" feeling :D
<img src="https://cloud.githubusercontent.com/assets/6735650/18419968/82778b44-7867-11e6-8549-f4612249d2ab.jpg" width="40%" height="40%" >

**Comment by gsantner** [comment]
Checkout the changes in branch  sharp40. You need to change
`<path android:fillAlpha="1" android:fillColor="#207be6"` in `ic_launcher.xml` for the icon
and  `colors.xml` for app color scheme.

**Comment by 4ndyD** [comment]
I like green or blue, but I absolutely don't want blue in a UI because it [makes it more difficult to get to sleep after looking at it](https://justgetflux.com/research.html).

Consider this a public health issue affecting all your fellow mobile diasporians. A clean grey would be fine, as people can use Dimmer to redden that when necessary, or _any_ other colour would be a better idea.

**Comment by gsantner** [comment]
@4ndyD Thanks for your notice!
We plan to implement a chooser, so anyone can choose those colors:  See https://github.com/Diaspora-for-Android/diaspora-android/issues/56.

If you have an idea of better looking (and an appropiate scheme to the app) colors, build the app with the colors and send/attach screenshots. :)

**Comment by vanitasvitae** [comment]
Settings are also themed now.

**Comment by walrus543** [comment]
Please add a black theme (I mean black, not dark).

**Comment by gsantner** [comment]
@vanitasvitae Maybe theres some parameter available to add custom colors to colorchooser - to add "#000000". Otherwise I would add two buttons (Preference with TreeClick) below those 2 current options, reset theme to application default colors (settings `@color/primary and /accent`. And another option - set primary to black

**Comment by gsantner** [comment]
@Primokorn Implemented something nice. Stay tuned for the next release.

**Comment by gsantner** [comment]
Future discussion can be a own issue, or a combined project discussion ticket.
