### ISSUE TITLE
Show Aspect name as title

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#44]
#### General information
- **Device:** doesn't matter
- **Android Version:** doesn't matter
- **Pod:** doesn't matter
- **Diaspora pod version:** doesn't matter
- **App source:** (latest HEAD)
- **App version:** HEAD

I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/Diaspora-for-Android/diaspora-android/blob/master/CONTRIBUTING.md
#### Steps to reproduce
1. Open aspects page
2. open one aspects Stream (lets call it "Friends")
#### Expected result

What is the expected output?
Window title gets set to "Friends"

What do you see instead?
Window title shows "Aspects"

"Set window title to aspects name instead of "Ascpects" when viewing some aspects stream "

**Comment by gsantner** [comment]
Fixed in 
https://github.com/Diaspora-for-Android/diaspora-android/commit/4f148191f740ecfa4107e929a851b42a8b862d27 https://github.com/Diaspora-for-Android/diaspora-android/commit/4f8215beee842b6432860d2acd5931a59bf9b25c
