### ISSUE TITLE
Check for new Notifications via service

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#46]
#### General information
- **Device:** doesn't matter
- **Android Version:** doesn't matter
- **Pod:** doesn't matter
- **Diaspora pod version:** doesn't matter
- **App source:** doesn't matter
- **App version:** HEAD

#### Steps to reproduce
1. Open stream with unread notification
2. click notification icon and open the unread notification ("read it")
3. go back to stream via back button
#### Expected result

What is the expected output? 
Notifications counter reads zero

What do you see instead?
Notifications counter still shows new notification

This is caused by the webview reusing cached data.
If we change the notifications button to use a dedicated service that pulls updates everytime we visit a new page in the webview, the problem should be gone.
Related to #6

**Comment by gsantner** [comment]
This is an upstream Bug (or maybe feature). Happens also on desktop.  
If you visit the notifications page the visible notifications do not automatically get marked. you must click on `Mark all as read` or click on one entry to mark it as read.

**Comment by gsantner** [comment]
Merge to #6
