### ISSUE TITLE
Android notifications for new messages/pod notifications

### ISSUE THREAD

**Issue by gsantner** [gsantner/dandelion#6]
Display a notification when a new message comes in.  
Might be done in an service which runs at background and checks at an configurable interval.

**Comment by gsantner** [comment]
For a proper implementation we have to wait for methods in the diaspora API allowing this.

**Comment by Jeeppler** [comment]
What is the status of this issue? Is the diaspora API limitation still an issue?

**Comment by vanitasvitae** [comment]
Probably. There has been no more progress on the API afaik.

**Comment by gsantner** [comment]
In general - please comment on this when there are news upstream, else I think as said, we can't do anything about it and can't give an ETA. Only can suggest to contribute to diaspora/ganggo/socialhome itself.

**Comment by Jeeppler** [comment]
I overlooked that the fact that the status/wait for AP label was replaced with wait/maybe/upstream. I thought only the status/wait for API was removed and therefor the misunderstanding.

**Comment by profzelonka** [comment]
So uhh.. 7 years later - Any hope here? 
An app with notifications is, while essential, what sets the platform apart from others who can't implement this feature.. And I've gone thru so many already, no platform has notifications. Please, please tell me this is coming very soon or possible in some other way?

**Comment by gsantner** [comment]
Well no, dandelion is not in active development and basically on life support.

Just like diaspora itself I guess. When checking it, seems like the world is still in 2015, not really noticing something different/new :-).

**Comment by profzelonka** [comment]
I've got hope! diaspora is the fastest and cleanest platform, with current world events and twitter news I've noticed some are becoming more mindful of privacy, even nextcloud is building a fediverse plugin but I digress. 

What exactly would it take for dandelion to add notifications? Is there already an issue submitted at https://github.com/diaspora/diaspora/issues for the function that dandelion would need to use?

**Comment by gsantner** [comment]
Realistic honest said: It won't happen. 

Nobody contributed to dandelion effective since years and I don't use diaspora active nor think about implementing something here.

**Comment by gsantner** [comment]
Realistic honest said: It won't happen. 

Nobody contributed to dandelion effective since years and I don't use diaspora active nor think about implementing something here. Whatever you need or want, you need to look it up on your own (if it exists by now) and implement it. If you really want it.

**Comment by profzelonka** [comment]
Thanks for bringing the app this far! It's fantastic. 

I made a thread on the diaspora forum to discuss this going forward. I'm no dev but it's definitely a crucial feature I'll do what I can to at least try. https://discourse.diasporafoundation.org/t/android-app-notifications/4860

**Comment by gsantner** [comment]
Unfortunatley need to say that I haven't used diaspora i a while, and neither is any active development going on. Humbly said, probably the best approach is currently to open diaspora in a browser and make a web-shortcut.

**Comment by Flaburgan** [comment]
Please be aware that diaspora now has a native android application at https://github.com/jhass/insporation
It's not official yet and doesn't work for pods running the stable code of diaspora*, but can already be used is your pod is running the last develop code.
