### ISSUE TITLE
can't choose a picture to upload in new post

### ISSUE THREAD

**Issue by stragu** [gsantner/dandelion#62]
#### General information
- **Device:** Fairphone 1
- **Android Version:** Android 4.2
- **Pod:** joindiaspora.com
- **Diaspora pod version:** 0.6.0.0
- **App source:** F-Droid
- **App version:** 0.1.5

#### Steps to reproduce
1. Create a new post
#### Expected result

What is the expected output? 

The camera image should be there, and be clickable to add a picture (as it is when doing the same thing from a browser like Firefox for Android).

What do you see instead?

The camera is a question mark, and clicking it does nothing.

**Comment by stragu** [comment]
![screenshot_2016-08-28-23-22-36](https://cloud.githubusercontent.com/assets/1747497/18034097/d27efaaa-6d77-11e6-9314-d3df148dc927.png)

**Comment by vanitasvitae** [comment]
Can you open the "new-post-site" in a webbrowser on your phone and see, if the question mark disappears?

**Comment by vanitasvitae** [comment]
I just checked it myself, and I can't reproduce this. At least there is no error on geraspora.de (0.6.0.0-p375f23b2).

Also I doubt this is a problem on our side. Looks more like an upstream problem to me (an issue on diaspora's mobile site).

**Comment by stragu** [comment]
@vanitasvitae do you mean https://joindiaspora.com/status_messages/new ? In Firefox for Android, I can see the camera icon instead of the question mark, and I can click it too to attach a picture. In the stock Android browser on my phone (which I assume is the one DfA is using), the camera icon is replaced by a question mark, and same goes with the notification bell; however, I can press where the camera should be and attach a picture normally (see picture).

In DfA, I can not click the button at all (nothing pops up to choose an app to upload an attachment from).

![screenshot_2016-08-29-22-56-52](https://cloud.githubusercontent.com/assets/1747497/18052253/96f6e036-6e3c-11e6-965f-a9f08be717d3.png)

**Comment by vanitasvitae** [comment]
Hm thats strange. Unfortunately I'm on vaccation right now, but I'll see when I have time

**Comment by vanitasvitae** [comment]
@stragu I thought a little bit about the problem. If the issue also appears on the default browser, I guess this is an upstream issue (either of the webview/Android browser, or of diaspora). Could you open a new issue at diaspora's [issue tracker](https://github.com/diaspora/diaspora/issues)? It is important to mention, that the problem appears when using the stock browser.

**Comment by lupa18** [comment]
same here

**Comment by vanitasvitae** [comment]
@lupa18 Are you also using Android 4.2? What pod are you using?

@lupa18 @stragu Can you provide some information about the installed Android browser/Webview version?

**Comment by lupa18** [comment]
I'm with Cyanogenmod 13 (Android 6). I'm using diasp.org pod and Diaspora 0.1.5 (from f-droid)

**Comment by vanitasvitae** [comment]
@AugierLe42e You do have the same problem?

**Comment by ghost** [comment]
I think there's actually two seperated problems here:
1. the icon thing
2. the can't upload images thing.

I have the second one, indeed. But it's nothing new and I believe I remember seeing an issue about that. Anyway, I doubt it's related to d\* 0.6 because I also use the previous Diaspora-Native-Webapp and it works well on a 0.6 pod.

I use CM 13 and Diaspora-Native-Webapp on d-fr (d\* v.0.6.99) and DFA on diaspote (d\* v.0.6.99 too).

**Comment by vanitasvitae** [comment]
I don't experience either of the problems. I tested on multiple pods as well.

What exactly happens when you click the photo button in DfA? Nothing? Or is at least a dialog opening?

**Comment by ghost** [comment]
Dialog stating « _impossible de récupérer l'image_ » (erm, it's in french but translation would be something like _can't retreive image_). There was an issue [on the old repo](https://github.com/martinchodev/Diaspora-Native-WebApp/issues/54). I can help you debug when I have more time.

**Comment by vanitasvitae** [comment]
Just for the record: you gave the external storage permission to DfA?

Edit: I can definitely reproduce the issue the way @AugierLe42e experiences it when I withdraw the external storage permission...

**Comment by gsantner** [comment]
Comment about Permissions:
I got also the problem that couldnt upload after resetting app data. I previously had the permission accepted so it worked before.
We need to be sure the app has the permission, then it should work (this issue happens on Android 6+ at least) (because the new permission system)

**Comment by vanitasvitae** [comment]
I'm already working on that and added the permission thing.

For Android 4.2, the Problem seems a lot bigger... I'm testing around in an emulator now and it seems like there is a whole interface method missing. I added it, but on my emulator, the onActivityResult always gets StatusCanceled immediately, even though I didnt even clicked on an image yet.

**Comment by lupa18** [comment]
Here a screencast: https://youtu.be/x5PXIOVUYCA

**Comment by vanitasvitae** [comment]
@lupa18 Thanks for the video, I'll look further into it :+1:

**Comment by ghost** [comment]
> Just for the record: you gave the external storage permission to DfA?

I have the problem whether I activate or not the permissions.

**Comment by vanitasvitae** [comment]
Okay, I got the problem fixed on my 4.2 emulator. Now its time to clean up my horrible code :dancer:

**Comment by vanitasvitae** [comment]
If someone wants to test my changes, [here](https://vanitasvitae.no-ip.biz/nextcloud/index.php/s/5MfCscwk0MZC9a6) is an experimental build signed with my key (you will have to reinstall the app). I really hope, this fixes the issue at least on 4.2 devices.
€: This also adds a permission check for 5.0+ devices. So @Lupa18 and @AugierLe42e this might shine some light on whether the problem is permissions related or not.

**Comment by stragu** [comment]
Great, with your experimental build, I can now upload a picture. I can press the button (still a question mark icon though), it offers me to use Amaze or Gallery, I can choose a photo, it uploads and publishes fine.
![screenshot_2016-09-08-08-35-18](https://cloud.githubusercontent.com/assets/1747497/18331195/67b731f2-75a0-11e6-9723-b6261aaa8bb7.png)

Cheers!

**Comment by stragu** [comment]
@vanitasvitae, note that it was always possible for me to upload a picture with the stock browser, which makes me think the description in https://github.com/diaspora/diaspora/issues/7069 gives the wrong idea.
Now that you fixed my upload issue in DfA, the only problem that I can see across both DfA 0.1.6 and Browser 4.2.2-2015081400 is the missing icon issue (not a problem in Firefox for Android).

**Comment by vanitasvitae** [comment]
Thank you for pointing that out. I'll rename the issue in the diaspora bug tracker tomorrow. Also I'll leave this thread open for now, until I got feedback, whether the uploading issue is fixed for everyone. 

Good night everyone :)

Am 8. September 2016 01:16:50 MESZ, schrieb "Stéphane Guillou" notifications@github.com:

> @vanitasvitae, note that it was always possible for me to upload a
> picture with the stock browser, which makes me think the description in
> https://github.com/diaspora/diaspora/issues/7069 gives the wrong idea.
> Now that you fixed my upload issue in DfA, the only problem that I can
> see across both DfA 0.1.6 and Browser 4.2.2-2015081400 is the missing
> icon issue (not a problem in Firefox for Android).
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/62#issuecomment-245448401

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by stragu** [comment]
OK I've done some more testing, and I can confirm that:
- the impossible photo upload is not specific to Diaspora 0.6, I just tested it in a pod with 0.5.10.1 (Berlinspora) and the issue is the same.
- the icon issue (question mark instead of camera and notification bell, nothing where the new post icon should be) seems introduced with 0.6, at least when comparing the three pods I can test on (Berlinspora, Joindiaspora, Framasphere).

I am modifying the title of this issue accordingly.

**Comment by ghost** [comment]
Yep, @vanitasvitae, It works, now.

**Comment by vanitasvitae** [comment]
That's great news :D I'm happy :)

Am 8. September 2016 09:40:39 MESZ, schrieb Augier notifications@github.com:

> Yep, @vanitasvitae, It works, now.
> 
> ## 
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/62#issuecomment-245518431

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by vanitasvitae** [comment]
I'll close this issue now. @lupa18 if you still experience the issue on the next release/the experimental build, please feel free to reopen :+1:

**Comment by lupa18** [comment]
thanks a lot !!
