### ISSUE TITLE
Show tabs with different types of notifications

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#70]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD
#### Steps to reproduce
1. Click on the notifications bell
#### Expected result

What is the expected output? 
Notifications overview shows different tabs for different types of notifications

What do you see instead?
All notifications are listed at once

**Comment by vanitasvitae** [comment]
Notifications would have to be shown in their own Fragment with a TabBar at the top. Also the Fragments WebView would need a custom WebChromeClient to redirect most urls to the StreamFragment. That would be related to #69

**Comment by gsantner** [comment]
What are different types of notifications?
Diaspora itself has only one notification button, where all are unified. I think we should go in the same direction, so users do not get confused

**Comment by vanitasvitae** [comment]
This was suggested [here](https://pod.geraspora.de/posts/5252331). I didn't knew this was possible either. It may be worth a try though :)

**Comment by gsantner** [comment]
Ahhh, should have been mentioned :D

**Comment by vanitasvitae** [comment]
It would be really nice to have a dropdownmenu with the different notification types, that opens on a long click on the notification bell.
Unfortunately I do not know, how to implement that since you cant setOnLongClickListener on a MenuItem.

**Comment by vanitasvitae** [comment]
I implemented a first design here: https://github.com/Diaspora-for-Android/diaspora-android/tree/dropdown_notifications
Feedback needed!

**Comment by vanitasvitae** [comment]
This is now implemented :tada:
