### ISSUE TITLE
Add share option to customTabs

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#71]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD
#### Steps to reproduce
1. Open external link in customtab
#### Expected result

What is the expected output? 
There is a share option that allows sharing of the displayed url to other apps

What do you see instead?
No such option

**Comment by gsantner** [comment]
Located in overflow menu
