### ISSUE TITLE
Show full url in customTab

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#72]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD
#### Steps to reproduce
1. Open external link in customTab
#### Expected result

What is the expected output? 
Full url is shown in customTabs toolbar

What do you see instead?
Only the domain part (eg. example.com) is visible.

**Comment by vanitasvitae** [comment]
I think this is not possible?

**Comment by gsantner** [comment]
You can click the info button in the overflow menu
![tmp_29248-screenshot_20160922-104342-105513026](https://cloud.githubusercontent.com/assets/6735650/18741906/db655004-80b1-11e6-9c51-8a52ed6d89cc.png)

**Comment by vanitasvitae** [comment]
Yes it is possible to show the url by clicking on the lock symbol/website icon, but it would be nice to show the full url in the first place. But since that seems impossible and on can indeed see the url by clicking the icon, I'll close this issue :D
