### ISSUE TITLE
Getting a login screen when I try to post.

### ISSUE THREAD

**Issue by Rbagman** [gsantner/dandelion#74]
Diaspora is logged into my account but it's asking for a username/password; which don't work although it is correct. I've received the following email notice:

//////

We received a request with a wrong/missing CSRF token from your account. To prevent any possible damage you have been logged out.

For more information on CSRF see https://www.owasp.org/index.php/Cross-SiteRequestForgery_(CSRF).

Sorry,

The diaspora\* email robot!

//////
#### General information

Samsung Note 2
Android Version 4.4.2
Diaspora 0.1.6(8)

**Comment by gsantner** [comment]
How long did you not use the app? Seems like the cookie got invalid, which is an important security feature.

Try to go into settings -> Switch pod. Select your pod again, login should work again.

**Comment by vanitasvitae** [comment]
I really hope, that the diaspora API will be released in the near future. That would solve such issues...

**Comment by vanitasvitae** [comment]
@Rbagman did @gsantner s suggestion resolve the issue for you?

**Comment by Rbagman** [comment]
Thanks @gsantner,

Yes @vanitasvitae, this resolved the problem; it has been a couple of days since I posted a comment.

**Comment by vanitasvitae** [comment]
Great!
