### ISSUE TITLE
Issues in dev branch "rework_fragments"

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#75]
This is a list of issues in the development branch rework_fragments (https://github.com/Diaspora-for-Android/diaspora-android/tree/rework_fragments)
These issues do not affect the master branch!
- [ ] Repair missing entries after MainActivity.recreate()
- [ ] Repair duplicate entries after open-other-fragment->reopen-stream-via-slider-entry (showFragment() only adds new entries, but does not remove the old ones)
- [ ] Fix adding/removing nav-slider items do not always apply when returning from settings

**Comment by gsantner** [comment]
Maybe merge to issue no 69 / Add checkboxes below the others, seperated with an line?

**Comment by vanitasvitae** [comment]
Moved to #69
