### ISSUE TITLE
Ask to apply Orbot proxy preset when choosing a pod with an onion profile

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#83]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** some pod with an Onion address
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD
#### Steps to reproduce
1. Start app for first time or choose option "Change Account"
2. Select pod with onion address profile
3. Click ok
#### Expected result

**What is the expected output?** 
The onion login site gets loaded

**What do you see instead?**
Site can not be loaded due to no tor proxy configured

The App should set the orbot proxy automatically when a onion profile is selected.

**Comment by gsantner** [comment]
This isn't a bug, its a enhanchment :D.  It was intended yet, because Tor may listening on a different port than the default port. But we could add an addition question dialog which asks if you want to set default tor proxy.

**Comment by vanitasvitae** [comment]
It would be nice to show a little orbot onion next to pods that offer a hidden service.

**Comment by gsantner** [comment]
Done in #88
