### ISSUE TITLE
crawling public post but stopped

### ISSUE THREAD

**Issue by Candidesk8** [gsantner/dandelion#84]
#### General information
- *\* FairPhone FP1U :**
- *\* Android 4.2.2 :**
- *\* pod.framasphere.org :**
- *\* 0.6.0.0-pba27cf8f :**
- *\* F-Droid :**
- *\* 0.1.6 (8) :**
#### Steps to reproduce

This is a new bug report. I am still discovering the application :-)
1. went on public post
2. asked for more post
3. 
#### Expected result

**What is the expected output?** 

**What do you see instead?**
was redirected to my activity.

Screenshot on demand if needed 

07:56:17: onReceive()- Set title for subUrl /activity?max_time=1476683109
07:56:17: JavaScriptInterface.setUserProfile()
07:56:17: No PodUserProfile refresh needed
07:56:17: onReceive()- Set title for subUrl /activity?max_time=1476683109
07:56:17: onReceive()- Set title for subUrl /activity?max_time=1476683109
07:56:17: JavaScriptInterface.setUserProfile()
07:56:17: No PodUserProfile refresh needed
07:56:18: JavaScriptInterface.setUserProfile()
07:56:18: No PodUserProfile refresh needed
07:56:29: onNavigationItemsSelected()
07:56:29: onReceive()- Set title for subUrl /activity?max_time=1476683109
07:56:29: JavaScriptInterface.setUserProfile()
07:56:29: PodUserProfile needs refresh; Try to parse JSON
07:56:29: onReceive()- Set title for subUrl /activity?max_time=1476683109
07:56:29: onReceive()- Set title for subUrl /activity?max_time=1476683109
07:56:32: onReceive()- Set title for subUrl /stream
07:56:32: onReceive()- Set title for subUrl /stream
07:56:33: onReceive()- Set title for subUrl /stream
07:56:33: onReceive()- Set title for subUrl /stream
07:56:33: JavaScriptInterface.setUserProfile()
07:56:33: No PodUserProfile refresh needed
07:56:33: onReceive()- Set title for subUrl /stream
07:56:33: onReceive()- Set title for subUrl /stream
07:56:33: JavaScriptInterface.setUserProfile()
07:56:33: No PodUserProfile refresh needed
07:56:33: JavaScriptInterface.setUserProfile()
07:56:33: No PodUserProfile refres

**Comment by vanitasvitae** [comment]
Thats actuall an upstream bug in the mobile interface of Diaspora. Nothing wie can do about it :(

Am 17. Oktober 2016 19:03:47 MESZ, schrieb Candidesk8 notifications@github.com:

> #### General information
> - *\* FairPhone FP1U :**
> - *\* Android 4.2.2 :**
> - *\* pod.framasphere.org :**
> - *\* 0.6.0.0-pba27cf8f :**
> - *\* F-Droid :**
> - *\* 0.1.6 (8) :**
> 
> #### Steps to reproduce
> 
> This is a new bug report. I am still discovering the application :-)
> 1. went on public post
> 2. asked for more post
> 3. 
> 
> #### Expected result
> 
> **What is the expected output?** 
> 
> **What do you see instead?**
> was redirected to my activity.
> 
> Screenshot on demand if needed 
> 
> 07:56:17: onReceive()- Set title for subUrl
> /activity?max_time=1476683109
> 07:56:17: JavaScriptInterface.setUserProfile()
> 07:56:17: No PodUserProfile refresh needed
> 07:56:17: onReceive()- Set title for subUrl
> /activity?max_time=1476683109
> 07:56:17: onReceive()- Set title for subUrl
> /activity?max_time=1476683109
> 07:56:17: JavaScriptInterface.setUserProfile()
> 07:56:17: No PodUserProfile refresh needed
> 07:56:18: JavaScriptInterface.setUserProfile()
> 07:56:18: No PodUserProfile refresh needed
> 07:56:29: onNavigationItemsSelected()
> 07:56:29: onReceive()- Set title for subUrl
> /activity?max_time=1476683109
> 07:56:29: JavaScriptInterface.setUserProfile()
> 07:56:29: PodUserProfile needs refresh; Try to parse JSON
> 07:56:29: onReceive()- Set title for subUrl
> /activity?max_time=1476683109
> 07:56:29: onReceive()- Set title for subUrl
> /activity?max_time=1476683109
> 07:56:32: onReceive()- Set title for subUrl /stream
> 07:56:32: onReceive()- Set title for subUrl /stream
> 07:56:33: onReceive()- Set title for subUrl /stream
> 07:56:33: onReceive()- Set title for subUrl /stream
> 07:56:33: JavaScriptInterface.setUserProfile()
> 07:56:33: No PodUserProfile refresh needed
> 07:56:33: onReceive()- Set title for subUrl /stream
> 07:56:33: onReceive()- Set title for subUrl /stream
> 07:56:33: JavaScriptInterface.setUserProfile()
> 07:56:33: No PodUserProfile refresh needed
> 07:56:33: JavaScriptInterface.setUserProfile()
> 07:56:33: No PodUserProfile refres
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/84

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
