### ISSUE TITLE
Profile not updated on first start and takes some time to be fully loaded

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#85]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD
#### Steps to reproduce
1. Start app for first time and log in
2. Open navigation slider
3. Open followed hashtags
#### Expected result

**What is the expected output?** 
The profile picture/Profile name is correctly set to the users ones
There is a list of followed hastags in the followed Hashtags fragment

**What do you see instead?**
The profile picture and name are updated only at the second start of the app
The followed Hashtags take even some more time (second start + some browsing around) until they appear.

This might be an issue because a new user expects to see full functionality from the first start on. It might scare some new users away when they quickly check out the app and see that their hashtags are missing.

I guess this might be caused by some missing/non-functioning profile-update-listener?
Maybe the missing tags are caused by the webview not finishing loading?

**Comment by vanitasvitae** [comment]
Also credentials are sometimes not saved in the webview. To save the password the user has to browse around for some time. Otherwise they will get prompted to enter their password on the next app start.

**Comment by vanitasvitae** [comment]
The stream navslider entry is missing in the first start

**Comment by gsantner** [comment]
It is intendend to not show any of stream, profile, etc. at first start, or if no pod is chosen. 

Loading profile informations is always done. If nothing is available yet it isn't available yet. Nothing we can do about.

**Comment by vanitasvitae** [comment]
The stream item is actually missing AFTER I logged in (most other entriss are there AS they should, but stream is missing). It reappears after I restart the app. I did not change any Navslider settings (they are reset after switching pod anyways)

**Comment by gsantner** [comment]
The pod profile gets loaded as early as possible since https://github.com/Diaspora-for-Android/diaspora-android/commit/6e7ae16e333abfc495dc17873d2aeeb8cd111147 .
