### ISSUE TITLE
Onion pods do not work after change account

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#86]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** Any pod with a hidden service address
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

Right now, the app does not work properly with hidden service pods after account gets changed. I set the orbot proxy preset, but the webview stays white. It works after I close the app and restart it though.

**Comment by gsantner** [comment]
Done in #88
