### ISSUE TITLE
Force Closes Upon Share

### ISSUE THREAD

**Issue by ClubWDW** [gsantner/dandelion#9]
When using the native Android share in order to share Title And Text, it force closes. When just sharing text only, it works fine.

**Comment by gsantner** [comment]
We are currently discussing what comes next and will submit the corresponding issues to github soon.
You are right that doesn't work really well now, sharing will most likely see a whole new implementation, which will also resolve your issue.

**Comment by gsantner** [comment]
See #12

**Comment by ClubWDW** [comment]
So, then my question is this. . . .I see an update to version 1.5 dated
04/09/16. However, I also wee a warning that says "This app has been
discontinued in favor of Diaspora" which redirects to version 0.1.0, which
hasn't been updated since it came out on 03/30/16. Which is the one that is
actively being developed/updated?

On Fri, Apr 8, 2016 at 5:54 AM, Gregor Santner notifications@github.com
wrote:

> See #12
> https://github.com/Diaspora-for-Android/diaspora-android/issues/12
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Diaspora-for-Android/diaspora-android/issues/9#issuecomment-207375074

## 

Bryan Belt

I prefer to use encrypted email. My public key fingerprint is 8DB3 1568
E467 F703 2C63 E444 821C 645D EBDC 9F9A. Learn why your privacy matters by
watching this video - https://youtu.be/pcSlowAhvUk and then learn how to
protect and encrypt your email by watching this video -
https://youtu.be/Ro3MSBS9w-A

**Comment by gsantner** [comment]
The active developed app is this one.  
Diaspora by @scoute-dich  and Diaspora Web-App by @martinchodev has been merged into this project, and both brought a last version which just redirects to here.

**Comment by gsantner** [comment]
@ClubWDW Diaspora v0.1.1 was released today. A note was also added to README that this is the latest one.
https://github.com/Diaspora-for-Android/diaspora-android/releases/tag/v0.1.1
