### ISSUE TITLE
Top Toolbar can be scrolled up, but not down in PodSelectionFragment

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#91]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD
#### Steps to reproduce
1. Have Intellihide toolbars enabled
2. Go to podselection
3. scroll ON the toolbar to hide it
#### Expected result

**What is the expected output?** 
Toolbar is scrollable no matter where the user scrolls
Also the toolbar, once hidden, can be shown again by scrolling somewhere else

**What do you see instead?**
The Toolbar only moves when the user scrolls on the toolbar itself
Once hidden, the toolbar cannot be shown again (because the user cant scroll on it anymore)

I guess we should disable intellihide toolbar in the PodSelectionFragment, since ListViews do not work with NestedScrollViews which are needed in order to enable screen-wide toolbar scrolling

**Comment by gsantner** [comment]
Scrolling Toolbar now working (>= API 21).
To get it also working on older versions, a port to RecycleView would be needed. But as the Filter&Search&Porting Stuff (and dynamically updating) is a lot of work, and this is only a small visual problem sometimes, I would say this is low priority.

**Comment by vanitasvitae** [comment]
Maybe disable it in that Fragment if API < 21?

**Comment by vanitasvitae** [comment]
I disabled scrolling in the PodSelectionFragment
