### ISSUE TITLE
Create "Lock Screen Rotation" option in settings

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#92]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** eg 0.1.5, or commit

This is a requested Feature, see #87. The user should be able to disable orientation changes in DiasporaForAndroid

**Comment by gsantner** [comment]
Some copy-pasta from one of my works:
(May be helpful)

```
    private static int orientationMode = 0;
    private void nextOrientation() {
        if (orientationMode++ > 2){
            orientationMode = 0;
       }
        int newOrient = ActivityInfo.SCREEN_ORIENTATION_SENSOR;
        switch (orientationMode) {
            case 1: {
                newOrient = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
                break;
            }
            case 2: {
                newOrient = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT;
                break;
            }
        }
        setRequestedOrientation(newOrient);
    }
```

Calling this function switches between `Disable,Sensor,Landscape,Portrait`-Orientation.

**Comment by vanitasvitae** [comment]
Can be fixed by applying #125

**Comment by noplanman** [comment]
I just saw that this is quite a recent change.

Why doesn't dandelion just follow the system setting for screen rotation?
I find myself having to change the setting in 2 places every time.

In my opinion, it would make sense to have "Automatic" obey to the system setting.

**Comment by vanitasvitae** [comment]
> In my opinion, it would make sense to have "Automatic" obey to the system setting.

Thats what we wanted to achieve. I guess, I did not test that feature properly :) We'll fix that.

**Comment by gsantner** [comment]
* Horizontal (fixed)
* Vertical (fixed)
* By system
* By sensor (ignore system settings)

**Comment by 85pando** [comment]
I think the "obey system default" should be the default option, as it is how users probably expect the app to behave.

Also, the "obey system default" seems not to be present in the 0.2.1 install from F-Droid.

**Comment by gsantner** [comment]
@noplanman @85pando
PR's are always welcome!

**Comment by noplanman** [comment]
🎉 Looking forward to the next release 😊

**Comment by gsantner** [comment]
@noplanman  <https://github.com/Diaspora-for-Android/dandelion/releases/tag/v0.2.2>

**Comment by noplanman** [comment]
Perfect! Thanks @gsantner 😇
