### ISSUE TITLE
Add debug feature that wipes all settings

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#93]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

It would be nice to have a feature in the app that clears all settings (app and pods).
We could forward users with strange issues to that option instead of figuring out, how the user can delete that settings manually.

**Comment by gsantner** [comment]
prefApp/prefPod.clear() would do the job.
Notice: Do quit (`System.exit()`) application afterwards, to be sure that no old data is still loaded somewhere.

**Comment by vanitasvitae** [comment]
This is now implemented
