### ISSUE TITLE
Accent color option shows wrong preview color on first start

### ISSUE THREAD

**Issue by vanitasvitae** [gsantner/dandelion#95]
#### General information
- **Device:** eg Nexus 5
- **Android Version:** eg Android 6.0.1
- **Pod:** eg pod.geraspora.de
- **Diaspora pod version:** eg 0.5.99.0-p9bd2337c  (can be found on the bottom)
- **App source:** F-Droid, self build (latest HEAD)
- **App version:** HEAD

#### Steps to reproduce
1. Start app for first time
2. Go to settings -> theme colors
#### Expected result

**What is the expected output?** 
Accent color option shows correct preview of accent color (orange by default)

**What do you see instead?**
Shown color is blue (default value of appSettings.getColor() )

I don't know a quick fix for that (apart of dirty hax)

**Comment by gsantner** [comment]
```
    public int getColor(String key) {
        return prefApp.getInt(key, context.getResources().getColor(R.color.primary));
    }
```

gets called in `circle.setColorFilter(appSettings.getColor(getKey()), PorterDuff.Mode.SRC_ATOP);` at `ThemedColorPickerPreference`. With default Value of prmary color ;)

Solution would be, that ThemedColorPickerPreference accepts an defaultValue in the xml.

**Comment by vanitasvitae** [comment]
I know, but I don't know, how to fix it in an easy and logical way... We could call appSettings.setAccentColor(appSettings.getAccentColor()) somewhere in APP Start (same for primary color), but thats ugly, right?

Am 25. Oktober 2016 21:56:31 MESZ schrieb Gregor Santner notifications@github.com:

> `
>    public int getColor(String key) {
> return prefApp.getInt(key,
> context.getResources().getColor(R.color.primary));
>    }
> `
> gets called in `circle.setColorFilter(appSettings.getColor(getKey()),
> PorterDuff.Mode.SRC_ATOP);` at `ThemedColorPickerPreference`. With
> default Value of prmary color ;)
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Diaspora-for-Android/diaspora-android/issues/95#issuecomment-256157713

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by gsantner** [comment]
Its already fixed ;)
